# ANALIZA DANYCH Z ZEGARKA APPLE WATCH


## Podstawowe informacje o pliku:

* Plik jest pobierany z aplikacji Zdrowie (Apple Health) na telefonie
* format: XML
* struktura: hierarchiczna, z wieloma różnymi typami rekordów (Record, Correlation, Workout, ActivitySummary, ClinicalRecord, Audiogram, VisionPrescription)
* zawiera dane dotyczące zdrowia, aktywności, snu, tętna, kroków, itp.
* jest dość duży ponad 700 mb

## TO DO:
1. [x] rozgryźć strukturę pliku xml - pól w nim zawartych - co dokładnie w nim jest
2. [x] sprawdzić pomiar EKG i możliwość ściągnięcia danych
3. [x] napisać kod pythona do wczytania tych danych
4. [x] zastanowić się nad programem ćwiczeń dla osób o różnej kondycji, z pomiarem zegarkiem

In [150]:
import os
import streamlit as st
import time

from altair.datasets import data
from lxml import etree as ET
import pandas as pd
from parser import load_one_type, load_all_health_data

In [151]:
path = "eksport.xml"

In [152]:
def discover_xml_structure(file_path):
    # Słownik: Klucz = Nazwa Tagu, Wartość = Zbiór atrybutów 'type' lub 'workoutActivityType'
    found_structures = {}

    context = ET.iterparse(file_path, events=("end",))

    for event, elem in context:
        tag_name = elem.tag

        #  dodajemy do slownika jesli nie ma w nim jeszcze
        if tag_name not in found_structures:
            found_structures[tag_name] = set()

        # sprawdzamy typy głównych tagów
        sub_type = elem.get("type") or elem.get("workoutActivityType") or "Brak"

        found_structures[tag_name].add(sub_type)

        # Czyścimy RAM
        elem.clear()

    return found_structures

moje_dane = discover_xml_structure(path)

print("ODKRYTE TAGI + typy danych")
for tag, sub_types in moje_dane.items():
    print(f"\n TAG: <{tag}>")
    print(f"   Liczba różnych typów: {len(sub_types)}")
    for st in list(sub_types):
        print(f"     - {st}")

ODKRYTE TAGI + typy danych

 TAG: <ExportDate>
   Liczba różnych typów: 1
     - Brak

 TAG: <Me>
   Liczba różnych typów: 1
     - Brak

 TAG: <Record>
   Liczba różnych typów: 41
     - HKQuantityTypeIdentifierStairDescentSpeed
     - HKQuantityTypeIdentifierEnvironmentalSoundReduction
     - HKQuantityTypeIdentifierWalkingHeartRateAverage
     - HKQuantityTypeIdentifierHeadphoneAudioExposure
     - HKCategoryTypeIdentifierMenstrualFlow
     - HKDataTypeSleepDurationGoal
     - HKQuantityTypeIdentifierHeartRate
     - HKCategoryTypeIdentifierAudioExposureEvent
     - HKQuantityTypeIdentifierVO2Max
     - HKQuantityTypeIdentifierBodyMass
     - HKQuantityTypeIdentifierBodyFatPercentage
     - HKQuantityTypeIdentifierBasalEnergyBurned
     - HKQuantityTypeIdentifierDistanceCycling
     - HKQuantityTypeIdentifierAppleExerciseTime
     - HKQuantityTypeIdentifierWalkingStepLength
     - HKQuantityTypeIdentifierAppleStandTime
     - HKQuantityTypeIdentifierHeartRateVariabilitySDNN
     - HKQuantityTypeIdentifierTimeInDaylight
     - HKQuantityTypeIdentifierOxygenSaturation
     - HKCategoryTypeIdentifierSleepAnalysis
     - HKQuantityTypeIdentifierWalkingSpeed
     - HKQuantityTypeIdentifierWalkingAsymmetryPercentage
     - HKQuantityTypeIdentifierHeartRateRecoveryOneMinute
     - HKQuantityTypeIdentifierStepCount
     - HKQuantityTypeIdentifierWaistCircumference
     - HKQuantityTypeIdentifierEnvironmentalAudioExposure
     - HKQuantityTypeIdentifierActiveEnergyBurned
     - HKQuantityTypeIdentifierDistanceWalkingRunning
     - HKQuantityTypeIdentifierStairAscentSpeed
     - HKCategoryTypeIdentifierHighHeartRateEvent
     - HKCategoryTypeIdentifierAppleStandHour
     - HKQuantityTypeIdentifierRestingHeartRate
     - HKQuantityTypeIdentifierPhysicalEffort
     - HKQuantityTypeIdentifierRespiratoryRate
     - HKQuantityTypeIdentifierFlightsClimbed
     - HKQuantityTypeIdentifierHeight
     - HKQuantityTypeIdentifierSixMinuteWalkTestDistance
     - HKQuantityTypeIdentifierAppleWalkingSteadiness
     - HKQuantityTypeIdentifierWalkingDoubleSupportPercentage
     - HKCategoryTypeIdentifierHeadphoneAudioExposureEvent
     - HKQuantityTypeIdentifierAppleSleepingWristTemperature

 TAG: <MetadataEntry>
   Liczba różnych typów: 1
     - Brak

 TAG: <WorkoutEvent>
   Liczba różnych typów: 4
     - HKWorkoutEventTypeMarker
     - HKWorkoutEventTypePause
     - HKWorkoutEventTypeResume
     - HKWorkoutEventTypeSegment

 TAG: <WorkoutStatistics>
   Liczba różnych typów: 5
     - HKQuantityTypeIdentifierActiveEnergyBurned
     - HKQuantityTypeIdentifierDistanceWalkingRunning
     - HKQuantityTypeIdentifierHeartRate
     - HKQuantityTypeIdentifierBasalEnergyBurned
     - HKQuantityTypeIdentifierDistanceCycling

 TAG: <Workout>
   Liczba różnych typów: 8
     - HKWorkoutActivityTypeFunctionalStrengthTraining
     - HKWorkoutActivityTypeCardioDance
     - HKWorkoutActivityTypeTennis
     - HKWorkoutActivityTypeCycling
     - HKWorkoutActivityTypeStairClimbing
     - HKWorkoutActivityTypePilates
     - HKWorkoutActivityTypeWalking
     - HKWorkoutActivityTypeElliptical

 TAG: <FileReference>
   Liczba różnych typów: 1
     - Brak

 TAG: <WorkoutRoute>
   Liczba różnych typów: 1
     - Brak

 TAG: <ActivitySummary>
   Liczba różnych typów: 1
     - Brak

 TAG: <InstantaneousBeatsPerMinute>
   Liczba różnych typów: 1
     - Brak

 TAG: <HeartRateVariabilityMetadataList>
   Liczba różnych typów: 1
     - Brak

 TAG: <HealthData>
   Liczba różnych typów: 1
     - Brak

In [153]:
important_tags = {
    'Me',"Record", "Workout", "ActivitySummary", "InstantaneousBeatsPerMinute"
}

In [154]:
print(moje_dane)

{'ExportDate': {'Brak'}, 'Me': {'Brak'}, 'Record': {'HKQuantityTypeIdentifierStairDescentSpeed', 'HKQuantityTypeIdentifierEnvironmentalSoundReduction', 'HKQuantityTypeIdentifierWalkingHeartRateAverage', 'HKQuantityTypeIdentifierHeadphoneAudioExposure', 'HKCategoryTypeIdentifierMenstrualFlow', 'HKDataTypeSleepDurationGoal', 'HKQuantityTypeIdentifierHeartRate', 'HKCategoryTypeIdentifierAudioExposureEvent', 'HKQuantityTypeIdentifierVO2Max', 'HKQuantityTypeIdentifierBodyMass', 'HKQuantityTypeIdentifierBodyFatPercentage', 'HKQuantityTypeIdentifierBasalEnergyBurned', 'HKQuantityTypeIdentifierDistanceCycling', 'HKQuantityTypeIdentifierAppleExerciseTime', 'HKQuantityTypeIdentifierWalkingStepLength', 'HKQuantityTypeIdentifierAppleStandTime', 'HKQuantityTypeIdentifierHeartRateVariabilitySDNN', 'HKQuantityTypeIdentifierTimeInDaylight', 'HKQuantityTypeIdentifierOxygenSaturation', 'HKCategoryTypeIdentifierSleepAnalysis', 'HKQuantityTypeIdentifierWalkingSpeed', 'HKQuantityTypeIdentifierWalkingAsymmetryPercentage', 'HKQuantityTypeIdentifierHeartRateRecoveryOneMinute', 'HKQuantityTypeIdentifierStepCount', 'HKQuantityTypeIdentifierWaistCircumference', 'HKQuantityTypeIdentifierEnvironmentalAudioExposure', 'HKQuantityTypeIdentifierActiveEnergyBurned', 'HKQuantityTypeIdentifierDistanceWalkingRunning', 'HKQuantityTypeIdentifierStairAscentSpeed', 'HKCategoryTypeIdentifierHighHeartRateEvent', 'HKCategoryTypeIdentifierAppleStandHour', 'HKQuantityTypeIdentifierRestingHeartRate', 'HKQuantityTypeIdentifierPhysicalEffort', 'HKQuantityTypeIdentifierRespiratoryRate', 'HKQuantityTypeIdentifierFlightsClimbed', 'HKQuantityTypeIdentifierHeight', 'HKQuantityTypeIdentifierSixMinuteWalkTestDistance', 'HKQuantityTypeIdentifierAppleWalkingSteadiness', 'HKQuantityTypeIdentifierWalkingDoubleSupportPercentage', 'HKCategoryTypeIdentifierHeadphoneAudioExposureEvent', 'HKQuantityTypeIdentifierAppleSleepingWristTemperature'}, 'MetadataEntry': {'Brak'}, 'WorkoutEvent': {'HKWorkoutEventTypeMarker', 'HKWorkoutEventTypePause', 'HKWorkoutEventTypeResume', 'HKWorkoutEventTypeSegment'}, 'WorkoutStatistics': {'HKQuantityTypeIdentifierActiveEnergyBurned', 'HKQuantityTypeIdentifierDistanceWalkingRunning', 'HKQuantityTypeIdentifierHeartRate', 'HKQuantityTypeIdentifierBasalEnergyBurned', 'HKQuantityTypeIdentifierDistanceCycling'}, 'Workout': {'HKWorkoutActivityTypeFunctionalStrengthTraining', 'HKWorkoutActivityTypeCardioDance', 'HKWorkoutActivityTypeTennis', 'HKWorkoutActivityTypeCycling', 'HKWorkoutActivityTypeStairClimbing', 'HKWorkoutActivityTypePilates', 'HKWorkoutActivityTypeWalking', 'HKWorkoutActivityTypeElliptical'}, 'FileReference': {'Brak'}, 'WorkoutRoute': {'Brak'}, 'ActivitySummary': {'Brak'}, 'InstantaneousBeatsPerMinute': {'Brak'}, 'HeartRateVariabilityMetadataList': {'Brak'}, 'HealthData': {'Brak'}}

In [155]:

diff_types = set()

diff_tags = set()
# Iterujemy po pliku
for event, elem in ET.iterparse(path, events=("end",)):
    if elem.tag in important_tags:
        typ = elem.get("type")  or elem.get("workoutActivityType") or elem.tag

        if typ not in diff_types:
            print(f"\n TYP: {typ}")
            print(f"   Atrybuty: {elem.attrib}")


            children = list(elem)
            if children:
                for child in children:
                    print(f"   typ: <{child.tag}> atrybuty: {child.attrib}")
            diff_types.add(typ)



        elem.clear()

 TYP: Me
   Atrybuty: {'HKCharacteristicTypeIdentifierDateOfBirth': '2006-03-02', 'HKCharacteristicTypeIdentifierBiologicalSex': 'HKBiologicalSexFemale', 'HKCharacteristicTypeIdentifierBloodType': 'HKBloodTypeNotSet', 'HKCharacteristicTypeIdentifierFitzpatrickSkinType': 'HKFitzpatrickSkinTypeNotSet', 'HKCharacteristicTypeIdentifierCardioFitnessMedicationsUse': 'Brak'}

 TYP: HKQuantityTypeIdentifierHeight
   Atrybuty: {'type': 'HKQuantityTypeIdentifierHeight', 'sourceName': 'FitnessOnline', 'sourceVersion': '206', 'unit': 'cm', 'creationDate': '2025-08-12 11:58:06 +0100', 'startDate': '2025-08-12 11:58:05 +0100', 'endDate': '2025-08-12 11:58:05 +0100', 'value': '163'}

 TYP: HKQuantityTypeIdentifierBodyMass
   Atrybuty: {'type': 'HKQuantityTypeIdentifierBodyMass', 'sourceName': 'Zdrowie', 'sourceVersion': '14.7.1', 'unit': 'kg', 'creationDate': '2021-09-06 10:46:43 +0100', 'startDate': '2021-09-06 10:46:00 +0100', 'endDate': '2021-09-06 10:46:00 +0100', 'value': '55'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKWasUserEntered', 'value': '1'}

 TYP: HKQuantityTypeIdentifierHeartRate
   Atrybuty: {'type': 'HKQuantityTypeIdentifierHeartRate', 'sourceName': 'Zepp Life', 'sourceVersion': '202112101619', 'unit': 'count/min', 'creationDate': '2021-12-24 16:29:14 +0100', 'startDate': '2021-12-17 00:00:00 +0100', 'endDate': '2021-12-17 00:00:59 +0100', 'value': '72'}

 TYP: HKQuantityTypeIdentifierOxygenSaturation
   Atrybuty: {'type': 'HKQuantityTypeIdentifierOxygenSaturation', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0x5c4acfe30>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': '%', 'creationDate': '2024-03-03 19:36:47 +0100', 'startDate': '2024-03-03 19:36:47 +0100', 'endDate': '2024-03-03 19:36:47 +0100', 'value': '0.99'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyBarometricPressure', 'value': '99.7209 kPa'}

 TYP: HKQuantityTypeIdentifierRespiratoryRate
   Atrybuty: {'type': 'HKQuantityTypeIdentifierRespiratoryRate', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0x5c4ace3a0>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': 'count/min', 'creationDate': '2024-03-03 21:40:34 +0100', 'startDate': '2024-03-03 21:37:30 +0100', 'endDate': '2024-03-03 21:37:30 +0100', 'value': '21'}

 TYP: HKQuantityTypeIdentifierBodyFatPercentage
   Atrybuty: {'type': 'HKQuantityTypeIdentifierBodyFatPercentage', 'sourceName': 'FitnessOnline', 'sourceVersion': '206', 'unit': '%', 'creationDate': '2025-08-12 11:58:06 +0100', 'startDate': '2025-08-12 11:58:05 +0100', 'endDate': '2025-08-12 11:58:05 +0100', 'value': '0'}

 TYP: HKQuantityTypeIdentifierStepCount
   Atrybuty: {'type': 'HKQuantityTypeIdentifierStepCount', 'sourceName': 'iPhone', 'sourceVersion': '13.6', 'device': '<<HKDevice: 0x5c4acd180>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:13.6, creation date:2020-07-29 09:04:05 +0000>', 'unit': 'count', 'creationDate': '2020-07-29 10:04:05 +0100', 'startDate': '2020-07-29 09:39:19 +0100', 'endDate': '2020-07-29 09:46:55 +0100', 'value': '12'}

 TYP: HKQuantityTypeIdentifierDistanceWalkingRunning
   Atrybuty: {'type': 'HKQuantityTypeIdentifierDistanceWalkingRunning', 'sourceName': 'iPhone', 'sourceVersion': '13.6', 'device': '<<HKDevice: 0x5c4acda40>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:13.6, creation date:2020-07-29 09:04:05 +0000>', 'unit': 'km', 'creationDate': '2020-07-29 10:04:05 +0100', 'startDate': '2020-07-29 09:39:19 +0100', 'endDate': '2020-07-29 09:46:55 +0100', 'value': '0.00712'}

 TYP: HKQuantityTypeIdentifierBasalEnergyBurned
   Atrybuty: {'type': 'HKQuantityTypeIdentifierBasalEnergyBurned', 'sourceName': 'iPhone', 'sourceVersion': '16.0', 'device': '<<HKDevice: 0x5c4ace990>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:16.0, creation date:2022-09-13 20:34:48 +0000>', 'unit': 'kcal', 'creationDate': '2022-09-13 21:34:48 +0100', 'startDate': '2022-09-12 21:35:44 +0100', 'endDate': '2022-09-12 21:50:39 +0100', 'value': '13.153'}

 TYP: HKQuantityTypeIdentifierActiveEnergyBurned
   Atrybuty: {'type': 'HKQuantityTypeIdentifierActiveEnergyBurned', 'sourceName': 'Zepp Life', 'sourceVersion': '202203221509', 'unit': 'kcal', 'creationDate': '2022-05-18 21:38:17 +0100', 'startDate': '2022-02-22 07:10:00 +0100', 'endDate': '2022-02-22 07:19:59 +0100', 'value': '4'}

 TYP: HKQuantityTypeIdentifierFlightsClimbed
   Atrybuty: {'type': 'HKQuantityTypeIdentifierFlightsClimbed', 'sourceName': 'iPhone', 'sourceVersion': '13.6.1', 'device': '<<HKDevice: 0x5c4ace3a0>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:13.6.1, creation date:2020-08-21 16:31:18 +0000>', 'unit': 'count', 'creationDate': '2020-08-23 13:12:47 +0100', 'startDate': '2020-08-23 13:00:22 +0100', 'endDate': '2020-08-23 13:00:25 +0100', 'value': '1'}

 TYP: HKQuantityTypeIdentifierAppleExerciseTime
   Atrybuty: {'type': 'HKQuantityTypeIdentifierAppleExerciseTime', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0x5c4acff70>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': 'min', 'creationDate': '2024-03-04 08:05:20 +0100', 'startDate': '2024-03-04 08:03:00 +0100', 'endDate': '2024-03-04 08:04:00 +0100', 'value': '1'}

 TYP: HKQuantityTypeIdentifierDistanceCycling
   Atrybuty: {'type': 'HKQuantityTypeIdentifierDistanceCycling', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.4', 'device': '<<HKDevice: 0x5c4acc2d0>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.4, creation date:2024-03-23 21:29:37 +0000>', 'unit': 'km', 'creationDate': '2024-06-11 18:45:23 +0100', 'startDate': '2024-06-11 18:43:00 +0100', 'endDate': '2024-06-11 18:43:29 +0100', 'value': '0.104494'}

 TYP: HKQuantityTypeIdentifierWaistCircumference
   Atrybuty: {'type': 'HKQuantityTypeIdentifierWaistCircumference', 'sourceName': 'FitnessOnline', 'sourceVersion': '206', 'unit': 'cm', 'creationDate': '2025-08-12 11:58:06 +0100', 'startDate': '2025-08-12 11:58:05 +0100', 'endDate': '2025-08-12 11:58:05 +0100', 'value': '0'}

 TYP: HKQuantityTypeIdentifierRestingHeartRate
   Atrybuty: {'type': 'HKQuantityTypeIdentifierRestingHeartRate', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'unit': 'count/min', 'creationDate': '2024-03-03 17:56:52 +0100', 'startDate': '2024-03-03 16:10:22 +0100', 'endDate': '2024-03-03 17:55:09 +0100', 'value': '72'}

 TYP: HKQuantityTypeIdentifierVO2Max
   Atrybuty: {'type': 'HKQuantityTypeIdentifierVO2Max', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '2890.8.3', 'unit': 'mL/min·kg', 'creationDate': '2024-03-05 12:07:27 +0100', 'startDate': '2024-03-05 12:07:27 +0100', 'endDate': '2024-03-05 12:07:27 +0100', 'value': '26.31'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKVO2MaxTestType', 'value': '2'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeySyncVersion', 'value': '1'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeySyncIdentifier', 'value': '3BA9D79C-F29B-4EAF-A67E-537BC3F23BBD'}

 TYP: HKQuantityTypeIdentifierWalkingHeartRateAverage
   Atrybuty: {'type': 'HKQuantityTypeIdentifierWalkingHeartRateAverage', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3.1', 'unit': 'count/min', 'creationDate': '2024-03-05 22:29:13 +0100', 'startDate': '2024-03-04 00:00:36 +0100', 'endDate': '2024-03-04 23:56:10 +0100', 'value': '118'}

 TYP: HKQuantityTypeIdentifierEnvironmentalAudioExposure
   Atrybuty: {'type': 'HKQuantityTypeIdentifierEnvironmentalAudioExposure', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0x5c4acd0e0>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': 'dBASPL', 'creationDate': '2024-03-03 16:15:55 +0100', 'startDate': '2024-03-03 16:05:54 +0100', 'endDate': '2024-03-03 16:35:53 +0100', 'value': '69.7388'}

 TYP: HKQuantityTypeIdentifierHeadphoneAudioExposure
   Atrybuty: {'type': 'HKQuantityTypeIdentifierHeadphoneAudioExposure', 'sourceName': 'iPhone', 'sourceVersion': '13.6.1', 'device': '<<HKDevice: 0x5c4accbe0>, name:EarPods, manufacturer:Apple Inc., localIdentifier:Wired Headphones, creation date:2020-08-30 20:08:43 +0000>', 'unit': 'dBASPL', 'creationDate': '2020-08-30 21:08:43 +0100', 'startDate': '2020-08-30 21:08:37 +0100', 'endDate': '2020-08-30 21:08:40 +0100', 'value': '62.366'}

 TYP: HKQuantityTypeIdentifierWalkingDoubleSupportPercentage
   Atrybuty: {'type': 'HKQuantityTypeIdentifierWalkingDoubleSupportPercentage', 'sourceName': 'iPhone', 'sourceVersion': '14.0', 'device': '<<HKDevice: 0x5c4acd590>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:14.0, creation date:2020-09-18 15:05:15 +0000>', 'unit': '%', 'creationDate': '2020-09-21 07:46:36 +0100', 'startDate': '2020-09-21 07:33:37 +0100', 'endDate': '2020-09-21 07:33:40 +0100', 'value': '0.329'}

 TYP: HKQuantityTypeIdentifierSixMinuteWalkTestDistance
   Atrybuty: {'type': 'HKQuantityTypeIdentifierSixMinuteWalkTestDistance', 'sourceName': 'iPhone', 'sourceVersion': '2890.12.17.0.3', 'unit': 'm', 'creationDate': '2024-03-14 16:50:03 +0100', 'startDate': '2024-03-14 16:50:03 +0100', 'endDate': '2024-03-14 16:50:03 +0100', 'value': '500'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKDateOfEarliestDataUsedForEstimate', 'value': '2024-03-02 23:00:00 +0000'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyAppleDeviceCalibrated', 'value': '1'}

 TYP: HKQuantityTypeIdentifierAppleStandTime
   Atrybuty: {'type': 'HKQuantityTypeIdentifierAppleStandTime', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '2890.8.3', 'unit': 'min', 'creationDate': '2024-03-03 16:20:11 +0100', 'startDate': '2024-03-03 16:15:00 +0100', 'endDate': '2024-03-03 16:20:00 +0100', 'value': '1'}

 TYP: HKQuantityTypeIdentifierWalkingSpeed
   Atrybuty: {'type': 'HKQuantityTypeIdentifierWalkingSpeed', 'sourceName': 'iPhone', 'sourceVersion': '14.0', 'device': '<<HKDevice: 0x5c4ace0d0>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:14.0, creation date:2020-09-18 15:05:15 +0000>', 'unit': 'km/hr', 'creationDate': '2020-09-21 07:46:36 +0100', 'startDate': '2020-09-21 07:33:37 +0100', 'endDate': '2020-09-21 07:33:40 +0100', 'value': '2.664'}

 TYP: HKQuantityTypeIdentifierWalkingStepLength
   Atrybuty: {'type': 'HKQuantityTypeIdentifierWalkingStepLength', 'sourceName': 'iPhone', 'sourceVersion': '14.0', 'device': '<<HKDevice: 0x5c4ace0d0>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:14.0, creation date:2020-09-18 15:05:15 +0000>', 'unit': 'cm', 'creationDate': '2020-09-21 07:46:36 +0100', 'startDate': '2020-09-21 07:33:37 +0100', 'endDate': '2020-09-21 07:33:40 +0100', 'value': '47'}

 TYP: HKQuantityTypeIdentifierWalkingAsymmetryPercentage
   Atrybuty: {'type': 'HKQuantityTypeIdentifierWalkingAsymmetryPercentage', 'sourceName': 'iPhone', 'sourceVersion': '14.0', 'device': '<<HKDevice: 0x5c4acd090>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:14.0, creation date:2020-09-18 15:05:15 +0000>', 'unit': '%', 'creationDate': '2020-09-21 08:39:37 +0100', 'startDate': '2020-09-21 07:35:02 +0100', 'endDate': '2020-09-21 07:35:19 +0100', 'value': '0'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyDevicePlacementSide', 'value': '2'}

 TYP: HKQuantityTypeIdentifierStairAscentSpeed
   Atrybuty: {'type': 'HKQuantityTypeIdentifierStairAscentSpeed', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '2890.8.3', 'unit': 'm/s', 'creationDate': '2024-03-04 08:04:47 +0100', 'startDate': '2024-03-04 08:03:56 +0100', 'endDate': '2024-03-04 08:04:05 +0100', 'value': '0.204918'}

 TYP: HKQuantityTypeIdentifierStairDescentSpeed
   Atrybuty: {'type': 'HKQuantityTypeIdentifierStairDescentSpeed', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '2890.8.3', 'unit': 'm/s', 'creationDate': '2024-03-04 09:43:24 +0100', 'startDate': '2024-03-04 09:42:44 +0100', 'endDate': '2024-03-04 09:42:48 +0100', 'value': '0.325972'}

 TYP: HKDataTypeSleepDurationGoal
   Atrybuty: {'type': 'HKDataTypeSleepDurationGoal', 'sourceName': 'Zdrowie', 'sourceVersion': '15.0', 'unit': 'hr', 'creationDate': '2021-10-04 12:32:04 +0100', 'startDate': '2021-10-04 12:32:04 +0100', 'endDate': '2021-10-04 12:32:04 +0100', 'value': '8'}

 TYP: HKQuantityTypeIdentifierAppleWalkingSteadiness
   Atrybuty: {'type': 'HKQuantityTypeIdentifierAppleWalkingSteadiness', 'sourceName': 'iPhone', 'sourceVersion': '2663.0.3', 'device': '<<HKDevice: 0x5c4acc3c0>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:15.0, creation date:2021-09-22 17:10:11 +0000>', 'unit': '%', 'creationDate': '2021-10-01 10:43:39 +0100', 'startDate': '2021-09-23 01:00:00 +0100', 'endDate': '2021-09-30 01:00:00 +0100', 'value': '0.980428'}

 TYP: HKQuantityTypeIdentifierAppleSleepingWristTemperature
   Atrybuty: {'type': 'HKQuantityTypeIdentifierAppleSleepingWristTemperature', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0x5c4acc640>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': 'degC', 'creationDate': '2024-03-04 07:00:17 +0100', 'startDate': '2024-03-03 23:00:00 +0100', 'endDate': '2024-03-04 07:00:16 +0100', 'value': '36.5868'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKAlgorithmVersion', 'value': '1'}

 TYP: HKQuantityTypeIdentifierHeartRateRecoveryOneMinute
   Atrybuty: {'type': 'HKQuantityTypeIdentifierHeartRateRecoveryOneMinute', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '2890.12.17.1.1', 'unit': 'count/min', 'creationDate': '2024-03-26 18:21:24 +0100', 'startDate': '2024-03-26 18:21:12 +0100', 'endDate': '2024-03-26 18:21:12 +0100', 'value': '34.9111'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyUserMotionContext', 'value': '1'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeySessionEstimate', 'value': '24.2808 count/min'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyHeartRateRecoveryActivityDuration', 'value': '1587.05 s'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyHeartRateRecoveryTestType', 'value': '2'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate', 'value': '150 count/min'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKAlgorithmVersion', 'value': '1'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyHeartRateRecoveryActivityType', 'value': '52'}

 TYP: HKQuantityTypeIdentifierEnvironmentalSoundReduction
   Atrybuty: {'type': 'HKQuantityTypeIdentifierEnvironmentalSoundReduction', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0x5c4acc780>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': 'dBASPL', 'creationDate': '2024-03-04 09:51:53 +0100', 'startDate': '2024-03-04 09:45:54 +0100', 'endDate': '2024-03-04 10:14:15 +0100', 'value': '23.6616'}

 TYP: HKQuantityTypeIdentifierTimeInDaylight
   Atrybuty: {'type': 'HKQuantityTypeIdentifierTimeInDaylight', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0x5c4acd9f0>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': 'min', 'creationDate': '2024-03-04 12:39:30 +0100', 'startDate': '2024-03-04 12:26:41 +0100', 'endDate': '2024-03-04 12:31:41 +0100', 'value': '5'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyMaximumLightIntensity', 'value': '7385 lx'}

 TYP: HKQuantityTypeIdentifierPhysicalEffort
   Atrybuty: {'type': 'HKQuantityTypeIdentifierPhysicalEffort', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '2890.8.3', 'unit': 'kcal/hr·kg', 'creationDate': '2024-03-03 16:32:44 +0100', 'startDate': '2024-03-03 16:04:44 +0100', 'endDate': '2024-03-03 16:31:53 +0100', 'value': '1.6'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKActivityType', 'value': '3000'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKAlgorithmVersion', 'value': '1'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKPhysicalEffortEstimationType', 'value': '2'}

 TYP: HKCategoryTypeIdentifierSleepAnalysis
   Atrybuty: {'type': 'HKCategoryTypeIdentifierSleepAnalysis', 'sourceName': 'iPhone', 'sourceVersion': '15.0', 'creationDate': '2021-10-05 06:00:00 +0100', 'startDate': '2021-10-04 22:11:07 +0100', 'endDate': '2021-10-05 05:41:01 +0100', 'value': 'HKCategoryValueSleepAnalysisInBed'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKTimeZone', 'value': 'Europe/Warsaw'}

 TYP: HKCategoryTypeIdentifierAppleStandHour
   Atrybuty: {'type': 'HKCategoryTypeIdentifierAppleStandHour', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0x5bfed4870>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'creationDate': '2024-03-03 16:19:59 +0100', 'startDate': '2024-03-03 16:00:00 +0100', 'endDate': '2024-03-03 17:00:00 +0100', 'value': 'HKCategoryValueAppleStandHourStood'}

 TYP: HKCategoryTypeIdentifierMenstrualFlow
   Atrybuty: {'type': 'HKCategoryTypeIdentifierMenstrualFlow', 'sourceName': 'Zdrowie', 'sourceVersion': '15.0', 'creationDate': '2021-10-04 12:32:53 +0100', 'startDate': '2021-10-03 11:00:00 +0100', 'endDate': '2021-10-03 11:00:00 +0100', 'value': 'HKCategoryValueVaginalBleedingUnspecified'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMenstrualCycleStart', 'value': '1'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKWasUserEntered', 'value': '1'}

 TYP: HKCategoryTypeIdentifierHighHeartRateEvent
   Atrybuty: {'type': 'HKCategoryTypeIdentifierHighHeartRateEvent', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '11.4', 'device': '<<HKDevice: 0x5bfed4190>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:11.4, creation date:2025-04-03 15:32:57 +0000>', 'creationDate': '2025-07-21 12:53:35 +0100', 'startDate': '2025-07-21 12:42:33 +0100', 'endDate': '2025-07-21 12:52:33 +0100', 'value': 'HKCategoryValueNotApplicable'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKHeartRateEventThreshold', 'value': '120 count/min'}

 TYP: HKCategoryTypeIdentifierAudioExposureEvent
   Atrybuty: {'type': 'HKCategoryTypeIdentifierAudioExposureEvent', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '1', 'device': '<<HKDevice: 0x5bfed6170>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.4, creation date:2024-03-23 21:29:37 +0000>', 'creationDate': '2024-05-24 16:16:06 +0100', 'startDate': '2024-05-24 16:13:08 +0100', 'endDate': '2024-05-24 16:16:06 +0100', 'value': 'HKCategoryValueEnvironmentalAudioExposureEventMomentaryLimit'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyAudioExposureLevel', 'value': '91.8655 dBASPL'}

 TYP: HKCategoryTypeIdentifierHeadphoneAudioExposureEvent
   Atrybuty: {'type': 'HKCategoryTypeIdentifierHeadphoneAudioExposureEvent', 'sourceName': 'iPhone', 'sourceVersion': '16.0.2', 'creationDate': '2022-12-04 14:31:26 +0100', 'startDate': '2022-11-27 04:43:02 +0100', 'endDate': '2022-12-04 14:31:26 +0100', 'value': 'HKCategoryValueHeadphoneAudioExposureEventSevenDayLimit'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyAudioExposureLevel', 'value': '93.8454 dBASPL'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyAudioExposureDuration', 'value': '5941.93 s'}


In [156]:
print(diff_types)
print(len(diff_types))

{'HKQuantityTypeIdentifierStairDescentSpeed', 'HKQuantityTypeIdentifierEnvironmentalSoundReduction', 'HKQuantityTypeIdentifierWalkingHeartRateAverage', 'HKQuantityTypeIdentifierHeadphoneAudioExposure', 'HKCategoryTypeIdentifierMenstrualFlow', 'HKDataTypeSleepDurationGoal', 'HKQuantityTypeIdentifierHeartRate', 'HKCategoryTypeIdentifierAudioExposureEvent', 'HKQuantityTypeIdentifierVO2Max', 'HKQuantityTypeIdentifierBodyMass', 'HKQuantityTypeIdentifierBodyFatPercentage', 'HKQuantityTypeIdentifierBasalEnergyBurned', 'InstantaneousBeatsPerMinute', 'HKQuantityTypeIdentifierDistanceCycling', 'HKQuantityTypeIdentifierAppleExerciseTime', 'HKQuantityTypeIdentifierWalkingStepLength', 'HKQuantityTypeIdentifierAppleStandTime', 'Me', 'HKQuantityTypeIdentifierHeartRateVariabilitySDNN', 'HKWorkoutActivityTypeCycling', 'HKQuantityTypeIdentifierTimeInDaylight', 'HKQuantityTypeIdentifierOxygenSaturation', 'HKCategoryTypeIdentifierSleepAnalysis', 'HKWorkoutActivityTypePilates', 'HKQuantityTypeIdentifierWalkingSpeed', 'HKQuantityTypeIdentifierWalkingAsymmetryPercentage', 'HKQuantityTypeIdentifierHeartRateRecoveryOneMinute', 'ActivitySummary', 'HKQuantityTypeIdentifierStepCount', 'HKQuantityTypeIdentifierWaistCircumference', 'HKQuantityTypeIdentifierEnvironmentalAudioExposure', 'HKWorkoutActivityTypeFunctionalStrengthTraining', 'HKQuantityTypeIdentifierActiveEnergyBurned', 'HKQuantityTypeIdentifierDistanceWalkingRunning', 'HKQuantityTypeIdentifierStairAscentSpeed', 'HKWorkoutActivityTypeTennis', 'HKWorkoutActivityTypeStairClimbing', 'HKCategoryTypeIdentifierHighHeartRateEvent', 'HKCategoryTypeIdentifierAppleStandHour', 'HKWorkoutActivityTypeElliptical', 'HKQuantityTypeIdentifierRestingHeartRate', 'HKQuantityTypeIdentifierPhysicalEffort', 'HKQuantityTypeIdentifierRespiratoryRate', 'HKQuantityTypeIdentifierFlightsClimbed', 'HKWorkoutActivityTypeCardioDance', 'HKQuantityTypeIdentifierHeight', 'HKQuantityTypeIdentifierSixMinuteWalkTestDistance', 'HKQuantityTypeIdentifierAppleWalkingSteadiness', 'HKQuantityTypeIdentifierWalkingDoubleSupportPercentage', 'HKCategoryTypeIdentifierHeadphoneAudioExposureEvent', 'HKQuantityTypeIdentifierAppleSleepingWristTemperature', 'HKWorkoutActivityTypeWalking'}
52

In [157]:
#Stworzenie dataframe z wybranym typem danych

short_names = {
    # --- CIAŁO / PODSTAWOWE ---
    'HKQuantityTypeIdentifierHeight': 'height',
    'HKQuantityTypeIdentifierBodyMass': 'weight',
    'HKQuantityTypeIdentifierWaistCircumference': 'waist',
    'HKQuantityTypeIdentifierBodyFatPercentage': 'fat_pct',

    # --- SERCE (HEART) ---
    'HKQuantityTypeIdentifierHeartRate': 'hr',
    'HKQuantityTypeIdentifierRestingHeartRate': 'rhr',
    'HKQuantityTypeIdentifierWalkingHeartRateAverage': 'hr_walk_avg',
    'HKQuantityTypeIdentifierHeartRateVariabilitySDNN': 'hrv',
    'HKQuantityTypeIdentifierHeartRateRecoveryOneMinute': 'hrr_1min',
    'HKCategoryTypeIdentifierHighHeartRateEvent': 'hr_high_event',

    # --- AKTYWNOŚĆ / ENERGIA ---
    'HKQuantityTypeIdentifierStepCount': 'steps',
    'HKQuantityTypeIdentifierDistanceWalkingRunning': 'dist_walk',
    'HKQuantityTypeIdentifierDistanceCycling': 'dist_cycle',
    'HKQuantityTypeIdentifierBasalEnergyBurned': 'kcal_basal',
    'HKQuantityTypeIdentifierActiveEnergyBurned': 'kcal_active',
    'HKQuantityTypeIdentifierFlightsClimbed': 'flights',
    'HKQuantityTypeIdentifierAppleExerciseTime': 'exercise_min',
    'HKQuantityTypeIdentifierAppleStandTime': 'stand_min',
    'HKCategoryTypeIdentifierAppleStandHour': 'stand_hr',
    'HKQuantityTypeIdentifierPhysicalEffort': 'effort',
    'HKQuantityTypeIdentifierVO2Max': 'vo2max',

    # --- MOBILNOŚĆ / CHÓD ---
    'HKQuantityTypeIdentifierWalkingSpeed': 'walk_speed',
    'HKQuantityTypeIdentifierWalkingStepLength': 'walk_step_len',
    'HKQuantityTypeIdentifierWalkingAsymmetryPercentage': 'walk_asym',
    'HKQuantityTypeIdentifierWalkingDoubleSupportPercentage': 'walk_dbl_supp',
    'HKQuantityTypeIdentifierStairAscentSpeed': 'stair_up_speed',
    'HKQuantityTypeIdentifierStairDescentSpeed': 'stair_down_speed',
    'HKQuantityTypeIdentifierAppleWalkingSteadiness': 'walk_steadiness',
    'HKQuantityTypeIdentifierSixMinuteWalkTestDistance': 'walk_6min',

    # --- ODDECH / POZIOMY ---
    'HKQuantityTypeIdentifierOxygenSaturation': 'spo2',
    'HKQuantityTypeIdentifierRespiratoryRate': 'resp_rate',

    # --- SEN ---
    'HKCategoryTypeIdentifierSleepAnalysis': 'sleep',
    'HKDataTypeSleepDurationGoal': 'sleep_goal',
    'HKQuantityTypeIdentifierAppleSleepingWristTemperature': 'wrist_temp',

    # --- ŚRODOWISKO / DŹWIĘK ---
    'HKQuantityTypeIdentifierEnvironmentalAudioExposure': 'audio_env',
    'HKQuantityTypeIdentifierHeadphoneAudioExposure': 'audio_hp',
    'HKQuantityTypeIdentifierEnvironmentalSoundReduction': 'sound_red',
    'HKCategoryTypeIdentifierAudioExposureEvent': 'audio_event',
    'HKCategoryTypeIdentifierHeadphoneAudioExposureEvent': 'audio_hp_event',
    'HKQuantityTypeIdentifierTimeInDaylight': 'daylight',

    # --- INNE ---
    'HKCategoryTypeIdentifierMenstrualFlow': 'menstr'
}

In [158]:
def load_one_type(file_path, tag_name, type_name=None):
    """
    Pobiera dane na podstawie samego tagu (np. 'ActivitySummary') lub tagu i typu (np. 'Record' + 'hr').
    Chirurgiczna pęseta do eksploracji danych.
    """
    health_data = []

    if file_path is None:
        return "Zła ścieżka pliku"

    context = ET.iterparse(file_path, events=("end",))

    for event, elem in context:

        if elem.tag == tag_name:
            current_type = elem.get('type') or elem.get('workoutActivityType')
            if type_name is None or current_type == type_name:
                record = dict(elem.attrib)

                for child in elem:
                    if child.tag == "MetadataEntry":
                        key = child.get('key')
                        if key is not None:
                            record[key] = child.get('value')
                health_data.append(record)

            elem.clear()

    if health_data:
        df = pd.DataFrame(health_data)
        if 'value' in df.columns:
            df['value'] = pd.to_numeric(df['value'], errors='coerce')
        for date_col in ['startDate', 'endDate', 'creationDate']:
            if date_col in df.columns:
                df[date_col] = pd.to_datetime(df[date_col])
        return df
    return pd.DataFrame()


df_hr = load_one_type(path, 'Record', 'HKQuantityTypeIdentifierHeartRate')
display(df_hr.head())

,type,sourceName,sourceVersion,unit,creationDate,startDate,endDate,value,device,HKMetadataKeyHeartRateMotionContext,HKMetadataKeySyncVersion,HKMetadataKeySyncIdentifier
0,HKQuantityTypeIdentifierHeartRate,Zepp Life,202112101619,count/min,2021-12-24 16:29:14+01:00,2021-12-17 00:00:00+01:00,2021-12-17 00:00:59+01:00,72.0,NaN,NaN,NaN,NaN
1,HKQuantityTypeIdentifierHeartRate,Zepp Life,202112101619,count/min,2021-12-24 16:29:14+01:00,2021-12-17 00:01:00+01:00,2021-12-17 00:01:59+01:00,70.0,NaN,NaN,NaN,NaN
2,HKQuantityTypeIdentifierHeartRate,Zepp Life,202112101619,count/min,2021-12-24 16:29:14+01:00,2021-12-17 00:02:00+01:00,2021-12-17 00:02:59+01:00,70.0,NaN,NaN,NaN,NaN
3,HKQuantityTypeIdentifierHeartRate,Zepp Life,202112101619,count/min,2021-12-24 16:29:14+01:00,2021-12-17 00:03:00+01:00,2021-12-17 00:03:59+01:00,69.0,NaN,NaN,NaN,NaN
4,HKQuantityTypeIdentifierHeartRate,Zepp Life,202112101619,count/min,2021-12-24 16:29:14+01:00,2021-12-17 00:04:00+01:00,2021-12-17 00:04:59+01:00,70.0,NaN,NaN,NaN,NaN

Analiza samych danych tetna

In [159]:
print(df_hr.columns)
print(df_hr.head())
print(df_hr.describe())

Index(['type', 'sourceName', 'sourceVersion', 'unit', 'creationDate',
       'startDate', 'endDate', 'value', 'device',
       'HKMetadataKeyHeartRateMotionContext', 'HKMetadataKeySyncVersion',
       'HKMetadataKeySyncIdentifier'],
      dtype='object')
                                type sourceName sourceVersion       unit  \
0  HKQuantityTypeIdentifierHeartRate  Zepp Life  202112101619  count/min
1  HKQuantityTypeIdentifierHeartRate  Zepp Life  202112101619  count/min
2  HKQuantityTypeIdentifierHeartRate  Zepp Life  202112101619  count/min
3  HKQuantityTypeIdentifierHeartRate  Zepp Life  202112101619  count/min
4  HKQuantityTypeIdentifierHeartRate  Zepp Life  202112101619  count/min

               creationDate                 startDate  \
0 2021-12-24 16:29:14+01:00 2021-12-17 00:00:00+01:00
1 2021-12-24 16:29:14+01:00 2021-12-17 00:01:00+01:00
2 2021-12-24 16:29:14+01:00 2021-12-17 00:02:00+01:00
3 2021-12-24 16:29:14+01:00 2021-12-17 00:03:00+01:00
4 2021-12-24 16:29:14+01:00 2021-12-17 00:04:00+01:00

                    endDate  value device HKMetadataKeyHeartRateMotionContext  \
0 2021-12-17 00:00:59+01:00   72.0    NaN                                 NaN
1 2021-12-17 00:01:59+01:00   70.0    NaN                                 NaN
2 2021-12-17 00:02:59+01:00   70.0    NaN                                 NaN
3 2021-12-17 00:03:59+01:00   69.0    NaN                                 NaN
4 2021-12-17 00:04:59+01:00   70.0    NaN                                 NaN

  HKMetadataKeySyncVersion HKMetadataKeySyncIdentifier
0                      NaN                         NaN
1                      NaN                         NaN
2                      NaN                         NaN
3                      NaN                         NaN
4                      NaN                         NaN
               value
count  401424.000000
mean       93.833004
std        28.793636
min        40.000000
25%        72.000000
50%        84.000000
75%       111.000000
max       195.000000

Czyścimy  dane - usuwamy kolumny w których wszystkie wartości sa nan

In [160]:
df_hr = df_hr.dropna(axis=1, how='all')

In [161]:
# Usuwamy konkretne kolumny techniczne, których nie potrzebujemy do analizy tętna
df_hr = df_hr.drop(columns=['HKMetadataKeySyncVersion', 'HKMetadataKeySyncIdentifier'], errors='ignore')

In [162]:
print(df_hr.columns)

Index(['type', 'sourceName', 'sourceVersion', 'unit', 'creationDate',
       'startDate', 'endDate', 'value', 'device',
       'HKMetadataKeyHeartRateMotionContext'],
      dtype='object')

In [163]:
# Usuwamy rekordy, które mają IDENTYCZNY start, koniec I wartość
df_hr = df_hr.drop_duplicates(subset=['startDate', 'endDate', 'value'])

print(f"Usunięto {len(df_hr) - len(df_hr)} idealnych duplikatów.")

Usunięto 0 idealnych duplikatów.

In [164]:

# bierzemy dane pobierane tylko z zegarka
df = df_hr[df_hr['sourceName'].str.contains('Apple', na=False)]


# Wywalamy rekordy, gdzie koniec jest przed początkiem i jakieś błędne
df = df[df['endDate'] >= df['startDate']]

# indeksujemy po dacie poczatkowej
df = df.set_index('startDate')

In [165]:
display(df.tail(100))

,type,sourceName,sourceVersion,unit,creationDate,endDate,value,device,HKMetadataKeyHeartRateMotionContext
startDate,,,,,,,,,
2026-03-05 14:31:23+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:31:26+01:00,2026-03-05 14:31:23+01:00,140.0,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
2026-03-05 14:31:31+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:31:31+01:00,2026-03-05 14:31:31+01:00,138.0,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
2026-03-05 14:31:33+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:31:37+01:00,2026-03-05 14:31:33+01:00,138.0,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
2026-03-05 14:31:37+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:31:42+01:00,2026-03-05 14:31:37+01:00,139.0,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
2026-03-05 14:31:45+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:31:47+01:00,2026-03-05 14:31:45+01:00,139.0,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
...,...,...,...,...,...,...,...,...,...
2026-03-05 14:39:22+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:39:27+01:00,2026-03-05 14:39:22+01:00,107.0,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
2026-03-05 14:39:27+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:39:32+01:00,2026-03-05 14:39:27+01:00,107.0,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
2026-03-05 14:39:32+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:39:37+01:00,2026-03-05 14:39:32+01:00,101.0,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
2026-03-05 14:39:56+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:39:57+01:00,2026-03-05 14:39:56+01:00,107.0,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
2026-03-05 15:00:28+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 15:04:30+01:00,2026-03-05 15:00:28+01:00,83.0,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",1

In [167]:

# 2. Definiujemy reguły: dla 'value' średnia, dla reszty 'pierwszy element'
# Tworzymy słownik, który dla każdej kolumny przypisuje funkcję 'first'
agg_rules = {col: 'first' for col in df.columns}

# Nadpisujemy regułę dla kolumny 'value' na 'mean'
if 'value' in agg_rules:
    agg_rules['value'] = 'mean'

# 3. Magiczne resamplowanie z regułami
df_minutowe = df.resample('1min').agg(agg_rules)

# 4. Przywracamy indeks do kolumny
df_minutowe = df_minutowe.reset_index()

display(df_minutowe)

,startDate,type,sourceName,sourceVersion,unit,creationDate,endDate,value,device,HKMetadataKeyHeartRateMotionContext
0,2024-03-03 16:10:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 16:10:31+01:00,2024-03-03 16:10:22+01:00,93.0,"<<HKDevice: 0x5c4ace260>, name:Apple Watch, ma...",1
1,2024-03-03 16:11:00+01:00,None,None,None,None,NaT,NaT,NaN,None,None
2,2024-03-03 16:12:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 16:16:07+01:00,2024-03-03 16:12:16+01:00,84.0,"<<HKDevice: 0x5c4ace260>, name:Apple Watch, ma...",1
3,2024-03-03 16:13:00+01:00,None,None,None,None,NaT,NaT,NaN,None,None
4,2024-03-03 16:14:00+01:00,None,None,None,None,NaT,NaT,NaN,None,None
...,...,...,...,...,...,...,...,...,...,...
1054006,2026-03-05 14:56:00+01:00,None,None,None,None,NaT,NaT,NaN,None,None
1054007,2026-03-05 14:57:00+01:00,None,None,None,None,NaT,NaT,NaN,None,None
1054008,2026-03-05 14:58:00+01:00,None,None,None,None,NaT,NaT,NaN,None,None
1054009,2026-03-05 14:59:00+01:00,None,None,None,None,NaT,NaT,NaN,None,None
1054010,2026-03-05 15:00:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 15:04:30+01:00,2026-03-05 15:00:28+01:00,83.0,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",1

In [168]:
df = df_minutowe.dropna()
display(df)

,startDate,type,sourceName,sourceVersion,unit,creationDate,endDate,value,device,HKMetadataKeyHeartRateMotionContext
0,2024-03-03 16:10:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 16:10:31+01:00,2024-03-03 16:10:22+01:00,93.000000,"<<HKDevice: 0x5c4ace260>, name:Apple Watch, ma...",1
2,2024-03-03 16:12:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 16:16:07+01:00,2024-03-03 16:12:16+01:00,84.000000,"<<HKDevice: 0x5c4ace260>, name:Apple Watch, ma...",1
8,2024-03-03 16:18:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 16:21:08+01:00,2024-03-03 16:18:43+01:00,82.000000,"<<HKDevice: 0x5c4ace260>, name:Apple Watch, ma...",1
14,2024-03-03 16:24:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 16:25:36+01:00,2024-03-03 16:24:23+01:00,80.000000,"<<HKDevice: 0x5c4ace260>, name:Apple Watch, ma...",1
15,2024-03-03 16:25:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 16:30:49+01:00,2024-03-03 16:25:28+01:00,78.000000,"<<HKDevice: 0x5c4ace260>, name:Apple Watch, ma...",1
...,...,...,...,...,...,...,...,...,...,...
1053986,2026-03-05 14:36:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:36:02+01:00,2026-03-05 14:36:01+01:00,112.615385,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
1053987,2026-03-05 14:37:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:37:07+01:00,2026-03-05 14:37:03+01:00,102.818182,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
1053988,2026-03-05 14:38:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:38:07+01:00,2026-03-05 14:38:02+01:00,90.272727,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
1053989,2026-03-05 14:39:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:39:02+01:00,2026-03-05 14:39:01+01:00,97.777778,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
1054010,2026-03-05 15:00:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 15:04:30+01:00,2026-03-05 15:00:28+01:00,83.000000,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",1

In [169]:

df.set_index('startDate', inplace=True)
df.sort_index(inplace=True)

In [170]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 168353 entries, 2024-03-03 16:10:00+01:00 to 2026-03-05 15:00:00+01:00
Data columns (total 9 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   type                                 168353 non-null  object
 1   sourceName                           168353 non-null  object
 2   sourceVersion                        168353 non-null  object
 3   unit                                 168353 non-null  object
 4   creationDate                         168353 non-null  datetime64[ns, UTC+01:00]
 5   endDate                              168353 non-null  datetime64[ns, UTC+01:00]
 6   value                                168353 non-null  float64
 7   device                               168353 non-null  object
 8   HKMetadataKeyHeartRateMotionContext  168353 non-null  object
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(6)
memory usage: 12.8+ MB

In [171]:
df = df.dropna(subset=['value'])
print(df.info())
df

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 168353 entries, 2024-03-03 16:10:00+01:00 to 2026-03-05 15:00:00+01:00
Data columns (total 9 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   type                                 168353 non-null  object
 1   sourceName                           168353 non-null  object
 2   sourceVersion                        168353 non-null  object
 3   unit                                 168353 non-null  object
 4   creationDate                         168353 non-null  datetime64[ns, UTC+01:00]
 5   endDate                              168353 non-null  datetime64[ns, UTC+01:00]
 6   value                                168353 non-null  float64
 7   device                               168353 non-null  object
 8   HKMetadataKeyHeartRateMotionContext  168353 non-null  object
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(6)
memory usage: 12.8+ MB
None

,type,sourceName,sourceVersion,unit,creationDate,endDate,value,device,HKMetadataKeyHeartRateMotionContext
startDate,,,,,,,,,
2024-03-03 16:10:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 16:10:31+01:00,2024-03-03 16:10:22+01:00,93.000000,"<<HKDevice: 0x5c4ace260>, name:Apple Watch, ma...",1
2024-03-03 16:12:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 16:16:07+01:00,2024-03-03 16:12:16+01:00,84.000000,"<<HKDevice: 0x5c4ace260>, name:Apple Watch, ma...",1
2024-03-03 16:18:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 16:21:08+01:00,2024-03-03 16:18:43+01:00,82.000000,"<<HKDevice: 0x5c4ace260>, name:Apple Watch, ma...",1
2024-03-03 16:24:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 16:25:36+01:00,2024-03-03 16:24:23+01:00,80.000000,"<<HKDevice: 0x5c4ace260>, name:Apple Watch, ma...",1
2024-03-03 16:25:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 16:30:49+01:00,2024-03-03 16:25:28+01:00,78.000000,"<<HKDevice: 0x5c4ace260>, name:Apple Watch, ma...",1
...,...,...,...,...,...,...,...,...,...
2026-03-05 14:36:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:36:02+01:00,2026-03-05 14:36:01+01:00,112.615385,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
2026-03-05 14:37:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:37:07+01:00,2026-03-05 14:37:03+01:00,102.818182,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
2026-03-05 14:38:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:38:07+01:00,2026-03-05 14:38:02+01:00,90.272727,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
2026-03-05 14:39:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:39:02+01:00,2026-03-05 14:39:01+01:00,97.777778,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
2026-03-05 15:00:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 15:04:30+01:00,2026-03-05 15:00:28+01:00,83.000000,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",1

In [172]:
df.loc['2026-3-3':]

,type,sourceName,sourceVersion,unit,creationDate,endDate,value,device,HKMetadataKeyHeartRateMotionContext
startDate,,,,,,,,,
2026-03-03 00:05:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-03 00:09:08+01:00,2026-03-03 00:05:13+01:00,84.000000,"<<HKDevice: 0x5c4acc7d0>, name:Apple Watch, ma...",0
2026-03-03 00:13:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-03 00:15:07+01:00,2026-03-03 00:13:34+01:00,79.000000,"<<HKDevice: 0x5c4acc7d0>, name:Apple Watch, ma...",0
2026-03-03 00:14:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-03 00:19:31+01:00,2026-03-03 00:14:50+01:00,81.000000,"<<HKDevice: 0x5c4acc7d0>, name:Apple Watch, ma...",0
2026-03-03 00:19:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-03 00:19:24+01:00,2026-03-03 00:19:24+01:00,97.000000,"<<HKDevice: 0x5c4acc7d0>, name:Apple Watch, ma...",0
2026-03-03 00:23:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-03 00:24:34+01:00,2026-03-03 00:23:10+01:00,84.000000,"<<HKDevice: 0x5c4acc7d0>, name:Apple Watch, ma...",0
...,...,...,...,...,...,...,...,...,...
2026-03-05 14:36:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:36:02+01:00,2026-03-05 14:36:01+01:00,112.615385,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
2026-03-05 14:37:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:37:07+01:00,2026-03-05 14:37:03+01:00,102.818182,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
2026-03-05 14:38:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:38:07+01:00,2026-03-05 14:38:02+01:00,90.272727,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
2026-03-05 14:39:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 14:39:02+01:00,2026-03-05 14:39:01+01:00,97.777778,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",2
2026-03-05 15:00:00+01:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-05 15:04:30+01:00,2026-03-05 15:00:28+01:00,83.000000,"<<HKDevice: 0x5c4acfe30>, name:Apple Watch, ma...",1

In [ ]:
df.loc['2024-03-01':'2024-03-05']

In [ ]:
%%sql