In [86]:
import os
import streamlit as st
import time
from parser import *
from lxml import etree as ET
import pandas as pd

### Plik jest pobierany z aplikacji Zdrowie (Apple Health) na telefonie, format pliku XML,

### Najważniejsze typy danych: **Record|Correlation|Workout|ActivitySummary** - reszte czyli ClinicalRecord|Audiogram|VisionPrescription pomijamy.

In [87]:
path = "eksport.xml"

In [187]:
def discover_xml_structure(file_path):
    # Słownik: Klucz = Nazwa Tagu, Wartość = Zbiór atrybutów 'type' lub 'workoutActivityType'
    found_structures = {}

    context = ET.iterparse(file_path, events=("end",))

    for event, elem in context:
        tag_name = elem.tag

        # Jeśli pierwszy raz widzimy ten tag, dodaj go do słownika
        if tag_name not in found_structures:
            found_structures[tag_name] = set()


        # Sprawdzamy, czy ten tag ma jakieś "podtypy" (np. HKQuantity...)
        sub_type = elem.get("type") or elem.get("workoutActivityType") or "Brak podtypu"

        found_structures[tag_name].add(sub_type)

        # Czyścimy RAM
        elem.clear()

    return found_structures

moje_dane = discover_xml_structure(path)

print("\n ODKRYTE ELEMENTY")
for tag, sub_types in moje_dane.items():
    print(f"\n TAG: <{tag}>")
    print(f"   Liczba różnych typów: {len(sub_types)}")
    for st in list(sub_types):
        print(f"     - {st}")

🚀 Skanuję plik w poszukiwaniu prawdy...

--- ODKRYTE ELEMENTY W TWOIM PLIKU ---

 TAG: <ExportDate>
   Liczba różnych typów: 1
     - Brak podtypu

 TAG: <Me>
   Liczba różnych typów: 1
     - Brak podtypu

 TAG: <Record>
   Liczba różnych typów: 41
     - HKQuantityTypeIdentifierWaistCircumference
     - HKQuantityTypeIdentifierVO2Max
     - HKQuantityTypeIdentifierSixMinuteWalkTestDistance
     - HKDataTypeSleepDurationGoal
     - HKQuantityTypeIdentifierFlightsClimbed
     - HKQuantityTypeIdentifierEnvironmentalAudioExposure
     - HKQuantityTypeIdentifierDistanceCycling
     - HKQuantityTypeIdentifierHeadphoneAudioExposure
     - HKQuantityTypeIdentifierStairDescentSpeed
     - HKQuantityTypeIdentifierHeartRateRecoveryOneMinute
     - HKQuantityTypeIdentifierBodyFatPercentage
     - HKQuantityTypeIdentifierTimeInDaylight
     - HKCategoryTypeIdentifierSleepAnalysis
     - HKCategoryTypeIdentifierAudioExposureEvent
     - HKQuantityTypeIdentifierDistanceWalkingRunning
     - HKQuantityTypeIdentifierAppleStandTime
     - HKCategoryTypeIdentifierMenstrualFlow
     - HKQuantityTypeIdentifierRestingHeartRate
     - HKQuantityTypeIdentifierStepCount
     - HKCategoryTypeIdentifierHighHeartRateEvent
     - HKQuantityTypeIdentifierAppleSleepingWristTemperature
     - HKQuantityTypeIdentifierWalkingDoubleSupportPercentage
     - HKQuantityTypeIdentifierWalkingSpeed
     - HKCategoryTypeIdentifierAppleStandHour
     - HKQuantityTypeIdentifierWalkingHeartRateAverage
     - HKQuantityTypeIdentifierRespiratoryRate
     - HKQuantityTypeIdentifierBodyMass
     - HKQuantityTypeIdentifierAppleWalkingSteadiness
     - HKQuantityTypeIdentifierBasalEnergyBurned
     - HKCategoryTypeIdentifierHeadphoneAudioExposureEvent
     - HKQuantityTypeIdentifierWalkingAsymmetryPercentage
     - HKQuantityTypeIdentifierStairAscentSpeed
     - HKQuantityTypeIdentifierEnvironmentalSoundReduction
     - HKQuantityTypeIdentifierOxygenSaturation
     - HKQuantityTypeIdentifierAppleExerciseTime
     - HKQuantityTypeIdentifierHeartRateVariabilitySDNN
     - HKQuantityTypeIdentifierWalkingStepLength
     - HKQuantityTypeIdentifierHeight
     - HKQuantityTypeIdentifierActiveEnergyBurned
     - HKQuantityTypeIdentifierPhysicalEffort
     - HKQuantityTypeIdentifierHeartRate

 TAG: <MetadataEntry>
   Liczba różnych typów: 1
     - Brak podtypu

 TAG: <WorkoutEvent>
   Liczba różnych typów: 4
     - HKWorkoutEventTypeMarker
     - HKWorkoutEventTypePause
     - HKWorkoutEventTypeResume
     - HKWorkoutEventTypeSegment

 TAG: <WorkoutStatistics>
   Liczba różnych typów: 5
     - HKQuantityTypeIdentifierDistanceWalkingRunning
     - HKQuantityTypeIdentifierActiveEnergyBurned
     - HKQuantityTypeIdentifierDistanceCycling
     - HKQuantityTypeIdentifierBasalEnergyBurned
     - HKQuantityTypeIdentifierHeartRate

 TAG: <Workout>
   Liczba różnych typów: 8
     - HKWorkoutActivityTypePilates
     - HKWorkoutActivityTypeWalking
     - HKWorkoutActivityTypeFunctionalStrengthTraining
     - HKWorkoutActivityTypeElliptical
     - HKWorkoutActivityTypeCardioDance
     - HKWorkoutActivityTypeTennis
     - HKWorkoutActivityTypeCycling
     - HKWorkoutActivityTypeStairClimbing

 TAG: <FileReference>
   Liczba różnych typów: 1
     - Brak podtypu

 TAG: <WorkoutRoute>
   Liczba różnych typów: 1
     - Brak podtypu

 TAG: <ActivitySummary>
   Liczba różnych typów: 1
     - Brak podtypu

 TAG: <InstantaneousBeatsPerMinute>
   Liczba różnych typów: 1
     - Brak podtypu

 TAG: <HeartRateVariabilityMetadataList>
   Liczba różnych typów: 1
     - Brak podtypu

 TAG: <HealthData>
   Liczba różnych typów: 1
     - Brak podtypu

In [190]:
important_tags = {
    'Me',"Record", "Workout", "WorkoutEvent", "WorkoutActivity",
    "WorkoutStatistics", "ActivitySummary", "InstantaneousBeatsPerMinute"
}

In [192]:

diff_types = set()

print("--- PRZEGLĄD STRUKTURY REKORDÓW ---")

# Iterujemy po pliku
for event, elem in ET.iterparse(path, events=("end",)):
    if elem.tag in important_tags:
        typ = elem.get("type") or elem.tag

        if typ not in diff_types:
            print(f"\n TYP: {typ}")
            print(f"   Atrybuty: {elem.attrib}")

            children = list(elem)
            if children:
                for child in children:
                    print(f"   └── Pod-element: <{child.tag}> atrybuty: {child.attrib}")

            diff_types.add(typ)



        elem.clear()

--- PRZEGLĄD STRUKTURY REKORDÓW ---

 TYP: Me
   Atrybuty: {'HKCharacteristicTypeIdentifierDateOfBirth': '2006-03-02', 'HKCharacteristicTypeIdentifierBiologicalSex': 'HKBiologicalSexFemale', 'HKCharacteristicTypeIdentifierBloodType': 'HKBloodTypeNotSet', 'HKCharacteristicTypeIdentifierFitzpatrickSkinType': 'HKFitzpatrickSkinTypeNotSet', 'HKCharacteristicTypeIdentifierCardioFitnessMedicationsUse': 'Brak'}

 TYP: HKQuantityTypeIdentifierHeight
   Atrybuty: {'type': 'HKQuantityTypeIdentifierHeight', 'sourceName': 'FitnessOnline', 'sourceVersion': '206', 'unit': 'cm', 'creationDate': '2025-08-12 11:58:06 +0100', 'startDate': '2025-08-12 11:58:05 +0100', 'endDate': '2025-08-12 11:58:05 +0100', 'value': '163'}

 TYP: HKQuantityTypeIdentifierBodyMass
   Atrybuty: {'type': 'HKQuantityTypeIdentifierBodyMass', 'sourceName': 'Zdrowie', 'sourceVersion': '14.7.1', 'unit': 'kg', 'creationDate': '2021-09-06 10:46:43 +0100', 'startDate': '2021-09-06 10:46:00 +0100', 'endDate': '2021-09-06 10:46:00 +0100', 'value': '55'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKWasUserEntered', 'value': '1'}

 TYP: HKQuantityTypeIdentifierHeartRate
   Atrybuty: {'type': 'HKQuantityTypeIdentifierHeartRate', 'sourceName': 'Zepp Life', 'sourceVersion': '202112101619', 'unit': 'count/min', 'creationDate': '2021-12-24 16:29:14 +0100', 'startDate': '2021-12-17 00:00:00 +0100', 'endDate': '2021-12-17 00:00:59 +0100', 'value': '72'}

 TYP: HKQuantityTypeIdentifierOxygenSaturation
   Atrybuty: {'type': 'HKQuantityTypeIdentifierOxygenSaturation', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0x5c4acfe30>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': '%', 'creationDate': '2024-03-03 19:36:47 +0100', 'startDate': '2024-03-03 19:36:47 +0100', 'endDate': '2024-03-03 19:36:47 +0100', 'value': '0.99'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyBarometricPressure', 'value': '99.7209 kPa'}

 TYP: HKQuantityTypeIdentifierRespiratoryRate
   Atrybuty: {'type': 'HKQuantityTypeIdentifierRespiratoryRate', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0x5c4ace3a0>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': 'count/min', 'creationDate': '2024-03-03 21:40:34 +0100', 'startDate': '2024-03-03 21:37:30 +0100', 'endDate': '2024-03-03 21:37:30 +0100', 'value': '21'}

 TYP: HKQuantityTypeIdentifierBodyFatPercentage
   Atrybuty: {'type': 'HKQuantityTypeIdentifierBodyFatPercentage', 'sourceName': 'FitnessOnline', 'sourceVersion': '206', 'unit': '%', 'creationDate': '2025-08-12 11:58:06 +0100', 'startDate': '2025-08-12 11:58:05 +0100', 'endDate': '2025-08-12 11:58:05 +0100', 'value': '0'}

 TYP: HKQuantityTypeIdentifierStepCount
   Atrybuty: {'type': 'HKQuantityTypeIdentifierStepCount', 'sourceName': 'iPhone', 'sourceVersion': '13.6', 'device': '<<HKDevice: 0x5c4acd180>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:13.6, creation date:2020-07-29 09:04:05 +0000>', 'unit': 'count', 'creationDate': '2020-07-29 10:04:05 +0100', 'startDate': '2020-07-29 09:39:19 +0100', 'endDate': '2020-07-29 09:46:55 +0100', 'value': '12'}

 TYP: HKQuantityTypeIdentifierDistanceWalkingRunning
   Atrybuty: {'type': 'HKQuantityTypeIdentifierDistanceWalkingRunning', 'sourceName': 'iPhone', 'sourceVersion': '13.6', 'device': '<<HKDevice: 0x5c4acda40>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:13.6, creation date:2020-07-29 09:04:05 +0000>', 'unit': 'km', 'creationDate': '2020-07-29 10:04:05 +0100', 'startDate': '2020-07-29 09:39:19 +0100', 'endDate': '2020-07-29 09:46:55 +0100', 'value': '0.00712'}

 TYP: HKQuantityTypeIdentifierBasalEnergyBurned
   Atrybuty: {'type': 'HKQuantityTypeIdentifierBasalEnergyBurned', 'sourceName': 'iPhone', 'sourceVersion': '16.0', 'device': '<<HKDevice: 0x5c4ace990>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:16.0, creation date:2022-09-13 20:34:48 +0000>', 'unit': 'kcal', 'creationDate': '2022-09-13 21:34:48 +0100', 'startDate': '2022-09-12 21:35:44 +0100', 'endDate': '2022-09-12 21:50:39 +0100', 'value': '13.153'}

 TYP: HKQuantityTypeIdentifierActiveEnergyBurned
   Atrybuty: {'type': 'HKQuantityTypeIdentifierActiveEnergyBurned', 'sourceName': 'Zepp Life', 'sourceVersion': '202203221509', 'unit': 'kcal', 'creationDate': '2022-05-18 21:38:17 +0100', 'startDate': '2022-02-22 07:10:00 +0100', 'endDate': '2022-02-22 07:19:59 +0100', 'value': '4'}

 TYP: HKQuantityTypeIdentifierFlightsClimbed
   Atrybuty: {'type': 'HKQuantityTypeIdentifierFlightsClimbed', 'sourceName': 'iPhone', 'sourceVersion': '13.6.1', 'device': '<<HKDevice: 0x5c4ace3a0>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:13.6.1, creation date:2020-08-21 16:31:18 +0000>', 'unit': 'count', 'creationDate': '2020-08-23 13:12:47 +0100', 'startDate': '2020-08-23 13:00:22 +0100', 'endDate': '2020-08-23 13:00:25 +0100', 'value': '1'}

 TYP: HKQuantityTypeIdentifierAppleExerciseTime
   Atrybuty: {'type': 'HKQuantityTypeIdentifierAppleExerciseTime', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0x5c4acff70>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': 'min', 'creationDate': '2024-03-04 08:05:20 +0100', 'startDate': '2024-03-04 08:03:00 +0100', 'endDate': '2024-03-04 08:04:00 +0100', 'value': '1'}

 TYP: HKQuantityTypeIdentifierDistanceCycling
   Atrybuty: {'type': 'HKQuantityTypeIdentifierDistanceCycling', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.4', 'device': '<<HKDevice: 0x5c4acc2d0>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.4, creation date:2024-03-23 21:29:37 +0000>', 'unit': 'km', 'creationDate': '2024-06-11 18:45:23 +0100', 'startDate': '2024-06-11 18:43:00 +0100', 'endDate': '2024-06-11 18:43:29 +0100', 'value': '0.104494'}

 TYP: HKQuantityTypeIdentifierWaistCircumference
   Atrybuty: {'type': 'HKQuantityTypeIdentifierWaistCircumference', 'sourceName': 'FitnessOnline', 'sourceVersion': '206', 'unit': 'cm', 'creationDate': '2025-08-12 11:58:06 +0100', 'startDate': '2025-08-12 11:58:05 +0100', 'endDate': '2025-08-12 11:58:05 +0100', 'value': '0'}

 TYP: HKQuantityTypeIdentifierRestingHeartRate
   Atrybuty: {'type': 'HKQuantityTypeIdentifierRestingHeartRate', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'unit': 'count/min', 'creationDate': '2024-03-03 17:56:52 +0100', 'startDate': '2024-03-03 16:10:22 +0100', 'endDate': '2024-03-03 17:55:09 +0100', 'value': '72'}

 TYP: HKQuantityTypeIdentifierVO2Max
   Atrybuty: {'type': 'HKQuantityTypeIdentifierVO2Max', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '2890.8.3', 'unit': 'mL/min·kg', 'creationDate': '2024-03-05 12:07:27 +0100', 'startDate': '2024-03-05 12:07:27 +0100', 'endDate': '2024-03-05 12:07:27 +0100', 'value': '26.31'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKVO2MaxTestType', 'value': '2'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeySyncVersion', 'value': '1'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeySyncIdentifier', 'value': '3BA9D79C-F29B-4EAF-A67E-537BC3F23BBD'}

 TYP: HKQuantityTypeIdentifierWalkingHeartRateAverage
   Atrybuty: {'type': 'HKQuantityTypeIdentifierWalkingHeartRateAverage', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3.1', 'unit': 'count/min', 'creationDate': '2024-03-05 22:29:13 +0100', 'startDate': '2024-03-04 00:00:36 +0100', 'endDate': '2024-03-04 23:56:10 +0100', 'value': '118'}

 TYP: HKQuantityTypeIdentifierEnvironmentalAudioExposure
   Atrybuty: {'type': 'HKQuantityTypeIdentifierEnvironmentalAudioExposure', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0x5c4acd0e0>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': 'dBASPL', 'creationDate': '2024-03-03 16:15:55 +0100', 'startDate': '2024-03-03 16:05:54 +0100', 'endDate': '2024-03-03 16:35:53 +0100', 'value': '69.7388'}

 TYP: HKQuantityTypeIdentifierHeadphoneAudioExposure
   Atrybuty: {'type': 'HKQuantityTypeIdentifierHeadphoneAudioExposure', 'sourceName': 'iPhone', 'sourceVersion': '13.6.1', 'device': '<<HKDevice: 0x5c4accbe0>, name:EarPods, manufacturer:Apple Inc., localIdentifier:Wired Headphones, creation date:2020-08-30 20:08:43 +0000>', 'unit': 'dBASPL', 'creationDate': '2020-08-30 21:08:43 +0100', 'startDate': '2020-08-30 21:08:37 +0100', 'endDate': '2020-08-30 21:08:40 +0100', 'value': '62.366'}

 TYP: HKQuantityTypeIdentifierWalkingDoubleSupportPercentage
   Atrybuty: {'type': 'HKQuantityTypeIdentifierWalkingDoubleSupportPercentage', 'sourceName': 'iPhone', 'sourceVersion': '14.0', 'device': '<<HKDevice: 0x5c4acd590>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:14.0, creation date:2020-09-18 15:05:15 +0000>', 'unit': '%', 'creationDate': '2020-09-21 07:46:36 +0100', 'startDate': '2020-09-21 07:33:37 +0100', 'endDate': '2020-09-21 07:33:40 +0100', 'value': '0.329'}

 TYP: HKQuantityTypeIdentifierSixMinuteWalkTestDistance
   Atrybuty: {'type': 'HKQuantityTypeIdentifierSixMinuteWalkTestDistance', 'sourceName': 'iPhone', 'sourceVersion': '2890.12.17.0.3', 'unit': 'm', 'creationDate': '2024-03-14 16:50:03 +0100', 'startDate': '2024-03-14 16:50:03 +0100', 'endDate': '2024-03-14 16:50:03 +0100', 'value': '500'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKDateOfEarliestDataUsedForEstimate', 'value': '2024-03-02 23:00:00 +0000'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyAppleDeviceCalibrated', 'value': '1'}

 TYP: HKQuantityTypeIdentifierAppleStandTime
   Atrybuty: {'type': 'HKQuantityTypeIdentifierAppleStandTime', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '2890.8.3', 'unit': 'min', 'creationDate': '2024-03-03 16:20:11 +0100', 'startDate': '2024-03-03 16:15:00 +0100', 'endDate': '2024-03-03 16:20:00 +0100', 'value': '1'}

 TYP: HKQuantityTypeIdentifierWalkingSpeed
   Atrybuty: {'type': 'HKQuantityTypeIdentifierWalkingSpeed', 'sourceName': 'iPhone', 'sourceVersion': '14.0', 'device': '<<HKDevice: 0x5c4ace0d0>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:14.0, creation date:2020-09-18 15:05:15 +0000>', 'unit': 'km/hr', 'creationDate': '2020-09-21 07:46:36 +0100', 'startDate': '2020-09-21 07:33:37 +0100', 'endDate': '2020-09-21 07:33:40 +0100', 'value': '2.664'}

 TYP: HKQuantityTypeIdentifierWalkingStepLength
   Atrybuty: {'type': 'HKQuantityTypeIdentifierWalkingStepLength', 'sourceName': 'iPhone', 'sourceVersion': '14.0', 'device': '<<HKDevice: 0x5c4ace0d0>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:14.0, creation date:2020-09-18 15:05:15 +0000>', 'unit': 'cm', 'creationDate': '2020-09-21 07:46:36 +0100', 'startDate': '2020-09-21 07:33:37 +0100', 'endDate': '2020-09-21 07:33:40 +0100', 'value': '47'}

 TYP: HKQuantityTypeIdentifierWalkingAsymmetryPercentage
   Atrybuty: {'type': 'HKQuantityTypeIdentifierWalkingAsymmetryPercentage', 'sourceName': 'iPhone', 'sourceVersion': '14.0', 'device': '<<HKDevice: 0x5c4acd090>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:14.0, creation date:2020-09-18 15:05:15 +0000>', 'unit': '%', 'creationDate': '2020-09-21 08:39:37 +0100', 'startDate': '2020-09-21 07:35:02 +0100', 'endDate': '2020-09-21 07:35:19 +0100', 'value': '0'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyDevicePlacementSide', 'value': '2'}

 TYP: HKQuantityTypeIdentifierStairAscentSpeed
   Atrybuty: {'type': 'HKQuantityTypeIdentifierStairAscentSpeed', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '2890.8.3', 'unit': 'm/s', 'creationDate': '2024-03-04 08:04:47 +0100', 'startDate': '2024-03-04 08:03:56 +0100', 'endDate': '2024-03-04 08:04:05 +0100', 'value': '0.204918'}

 TYP: HKQuantityTypeIdentifierStairDescentSpeed
   Atrybuty: {'type': 'HKQuantityTypeIdentifierStairDescentSpeed', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '2890.8.3', 'unit': 'm/s', 'creationDate': '2024-03-04 09:43:24 +0100', 'startDate': '2024-03-04 09:42:44 +0100', 'endDate': '2024-03-04 09:42:48 +0100', 'value': '0.325972'}

 TYP: HKDataTypeSleepDurationGoal
   Atrybuty: {'type': 'HKDataTypeSleepDurationGoal', 'sourceName': 'Zdrowie', 'sourceVersion': '15.0', 'unit': 'hr', 'creationDate': '2021-10-04 12:32:04 +0100', 'startDate': '2021-10-04 12:32:04 +0100', 'endDate': '2021-10-04 12:32:04 +0100', 'value': '8'}

 TYP: HKQuantityTypeIdentifierAppleWalkingSteadiness
   Atrybuty: {'type': 'HKQuantityTypeIdentifierAppleWalkingSteadiness', 'sourceName': 'iPhone', 'sourceVersion': '2663.0.3', 'device': '<<HKDevice: 0x5c4acc3c0>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:15.0, creation date:2021-09-22 17:10:11 +0000>', 'unit': '%', 'creationDate': '2021-10-01 10:43:39 +0100', 'startDate': '2021-09-23 01:00:00 +0100', 'endDate': '2021-09-30 01:00:00 +0100', 'value': '0.980428'}

 TYP: HKQuantityTypeIdentifierAppleSleepingWristTemperature
   Atrybuty: {'type': 'HKQuantityTypeIdentifierAppleSleepingWristTemperature', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0x5c4acc640>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': 'degC', 'creationDate': '2024-03-04 07:00:17 +0100', 'startDate': '2024-03-03 23:00:00 +0100', 'endDate': '2024-03-04 07:00:16 +0100', 'value': '36.5868'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKAlgorithmVersion', 'value': '1'}

 TYP: HKQuantityTypeIdentifierHeartRateRecoveryOneMinute
   Atrybuty: {'type': 'HKQuantityTypeIdentifierHeartRateRecoveryOneMinute', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '2890.12.17.1.1', 'unit': 'count/min', 'creationDate': '2024-03-26 18:21:24 +0100', 'startDate': '2024-03-26 18:21:12 +0100', 'endDate': '2024-03-26 18:21:12 +0100', 'value': '34.9111'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyUserMotionContext', 'value': '1'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeySessionEstimate', 'value': '24.2808 count/min'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyHeartRateRecoveryActivityDuration', 'value': '1587.05 s'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyHeartRateRecoveryTestType', 'value': '2'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate', 'value': '150 count/min'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKAlgorithmVersion', 'value': '1'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyHeartRateRecoveryActivityType', 'value': '52'}

 TYP: HKQuantityTypeIdentifierEnvironmentalSoundReduction
   Atrybuty: {'type': 'HKQuantityTypeIdentifierEnvironmentalSoundReduction', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0x5c4acc780>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': 'dBASPL', 'creationDate': '2024-03-04 09:51:53 +0100', 'startDate': '2024-03-04 09:45:54 +0100', 'endDate': '2024-03-04 10:14:15 +0100', 'value': '23.6616'}

 TYP: HKQuantityTypeIdentifierTimeInDaylight
   Atrybuty: {'type': 'HKQuantityTypeIdentifierTimeInDaylight', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0x5c4acd9f0>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': 'min', 'creationDate': '2024-03-04 12:39:30 +0100', 'startDate': '2024-03-04 12:26:41 +0100', 'endDate': '2024-03-04 12:31:41 +0100', 'value': '5'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyMaximumLightIntensity', 'value': '7385 lx'}

 TYP: HKQuantityTypeIdentifierPhysicalEffort
   Atrybuty: {'type': 'HKQuantityTypeIdentifierPhysicalEffort', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '2890.8.3', 'unit': 'kcal/hr·kg', 'creationDate': '2024-03-03 16:32:44 +0100', 'startDate': '2024-03-03 16:04:44 +0100', 'endDate': '2024-03-03 16:31:53 +0100', 'value': '1.6'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKActivityType', 'value': '3000'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKAlgorithmVersion', 'value': '1'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKPhysicalEffortEstimationType', 'value': '2'}

 TYP: HKCategoryTypeIdentifierSleepAnalysis
   Atrybuty: {'type': 'HKCategoryTypeIdentifierSleepAnalysis', 'sourceName': 'iPhone', 'sourceVersion': '15.0', 'creationDate': '2021-10-05 06:00:00 +0100', 'startDate': '2021-10-04 22:11:07 +0100', 'endDate': '2021-10-05 05:41:01 +0100', 'value': 'HKCategoryValueSleepAnalysisInBed'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKTimeZone', 'value': 'Europe/Warsaw'}

 TYP: HKCategoryTypeIdentifierAppleStandHour
   Atrybuty: {'type': 'HKCategoryTypeIdentifierAppleStandHour', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0x5bfed4870>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'creationDate': '2024-03-03 16:19:59 +0100', 'startDate': '2024-03-03 16:00:00 +0100', 'endDate': '2024-03-03 17:00:00 +0100', 'value': 'HKCategoryValueAppleStandHourStood'}

 TYP: HKCategoryTypeIdentifierMenstrualFlow
   Atrybuty: {'type': 'HKCategoryTypeIdentifierMenstrualFlow', 'sourceName': 'Zdrowie', 'sourceVersion': '15.0', 'creationDate': '2021-10-04 12:32:53 +0100', 'startDate': '2021-10-03 11:00:00 +0100', 'endDate': '2021-10-03 11:00:00 +0100', 'value': 'HKCategoryValueVaginalBleedingUnspecified'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKMenstrualCycleStart', 'value': '1'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKWasUserEntered', 'value': '1'}

 TYP: HKCategoryTypeIdentifierHighHeartRateEvent
   Atrybuty: {'type': 'HKCategoryTypeIdentifierHighHeartRateEvent', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '11.4', 'device': '<<HKDevice: 0x5bfed4190>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:11.4, creation date:2025-04-03 15:32:57 +0000>', 'creationDate': '2025-07-21 12:53:35 +0100', 'startDate': '2025-07-21 12:42:33 +0100', 'endDate': '2025-07-21 12:52:33 +0100', 'value': 'HKCategoryValueNotApplicable'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKHeartRateEventThreshold', 'value': '120 count/min'}

 TYP: HKCategoryTypeIdentifierAudioExposureEvent
   Atrybuty: {'type': 'HKCategoryTypeIdentifierAudioExposureEvent', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '1', 'device': '<<HKDevice: 0x5bfed6170>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.4, creation date:2024-03-23 21:29:37 +0000>', 'creationDate': '2024-05-24 16:16:06 +0100', 'startDate': '2024-05-24 16:13:08 +0100', 'endDate': '2024-05-24 16:16:06 +0100', 'value': 'HKCategoryValueEnvironmentalAudioExposureEventMomentaryLimit'}
   └── Pod-element: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyAudioExposureLevel', 'value': '91.8655 dBASPL'}

 TYP: HKCategoryTypeIdentifierHeadphoneAudioExposureEvent

In [90]:
#Stworzenie dataframe z wybranym typem danych

short_names = {
    # --- CIAŁO / PODSTAWOWE ---
    'HKQuantityTypeIdentifierHeight': 'height',
    'HKQuantityTypeIdentifierBodyMass': 'weight',
    'HKQuantityTypeIdentifierWaistCircumference': 'waist',
    'HKQuantityTypeIdentifierBodyFatPercentage': 'fat_pct',

    # --- SERCE (HEART) ---
    'HKQuantityTypeIdentifierHeartRate': 'hr',
    'HKQuantityTypeIdentifierRestingHeartRate': 'rhr',
    'HKQuantityTypeIdentifierWalkingHeartRateAverage': 'hr_walk_avg',
    'HKQuantityTypeIdentifierHeartRateVariabilitySDNN': 'hrv',
    'HKQuantityTypeIdentifierHeartRateRecoveryOneMinute': 'hrr_1min',
    'HKCategoryTypeIdentifierHighHeartRateEvent': 'hr_high_event',

    # --- AKTYWNOŚĆ / ENERGIA ---
    'HKQuantityTypeIdentifierStepCount': 'steps',
    'HKQuantityTypeIdentifierDistanceWalkingRunning': 'dist_walk',
    'HKQuantityTypeIdentifierDistanceCycling': 'dist_cycle',
    'HKQuantityTypeIdentifierBasalEnergyBurned': 'kcal_basal',
    'HKQuantityTypeIdentifierActiveEnergyBurned': 'kcal_active',
    'HKQuantityTypeIdentifierFlightsClimbed': 'flights',
    'HKQuantityTypeIdentifierAppleExerciseTime': 'exercise_min',
    'HKQuantityTypeIdentifierAppleStandTime': 'stand_min',
    'HKCategoryTypeIdentifierAppleStandHour': 'stand_hr',
    'HKQuantityTypeIdentifierPhysicalEffort': 'effort',
    'HKQuantityTypeIdentifierVO2Max': 'vo2max',

    # --- MOBILNOŚĆ / CHÓD ---
    'HKQuantityTypeIdentifierWalkingSpeed': 'walk_speed',
    'HKQuantityTypeIdentifierWalkingStepLength': 'walk_step_len',
    'HKQuantityTypeIdentifierWalkingAsymmetryPercentage': 'walk_asym',
    'HKQuantityTypeIdentifierWalkingDoubleSupportPercentage': 'walk_dbl_supp',
    'HKQuantityTypeIdentifierStairAscentSpeed': 'stair_up_speed',
    'HKQuantityTypeIdentifierStairDescentSpeed': 'stair_down_speed',
    'HKQuantityTypeIdentifierAppleWalkingSteadiness': 'walk_steadiness',
    'HKQuantityTypeIdentifierSixMinuteWalkTestDistance': 'walk_6min',

    # --- ODDECH / POZIOMY ---
    'HKQuantityTypeIdentifierOxygenSaturation': 'spo2',
    'HKQuantityTypeIdentifierRespiratoryRate': 'resp_rate',

    # --- SEN ---
    'HKCategoryTypeIdentifierSleepAnalysis': 'sleep',
    'HKDataTypeSleepDurationGoal': 'sleep_goal',
    'HKQuantityTypeIdentifierAppleSleepingWristTemperature': 'wrist_temp',

    # --- ŚRODOWISKO / DŹWIĘK ---
    'HKQuantityTypeIdentifierEnvironmentalAudioExposure': 'audio_env',
    'HKQuantityTypeIdentifierHeadphoneAudioExposure': 'audio_hp',
    'HKQuantityTypeIdentifierEnvironmentalSoundReduction': 'sound_red',
    'HKCategoryTypeIdentifierAudioExposureEvent': 'audio_event',
    'HKCategoryTypeIdentifierHeadphoneAudioExposureEvent': 'audio_hp_event',
    'HKQuantityTypeIdentifierTimeInDaylight': 'daylight',

    # --- INNE ---
    'HKCategoryTypeIdentifierMenstrualFlow': 'menstr'
}

In [91]:


def load_all_health_data(file_path, mapping):
    """
    Funkcja zwraca słownik DataFrameów z krótkimi nazwami, żeby szybciej wpisywać.
    """
    if file_path is None:
        return "Zła ścieżka pliku, spróbuj ponownie"
    if mapping is None:
        mapping = types_list # jeśli nie mamy krótkich nazw używamy pobranych długich

    # 1. Tworzymy puste listy dla każdego krótkiego skrótu ze słownika
    data_buckets = {short_name: [] for short_name in mapping.values()}

    # 2. Startujemy iterparse
    # event="end" oznacza, że reagujemy, gdy zamknie się tag </Record>
    context = ET.iterparse(file_path, events=("end",))

    print("🚀 Rozpoczynam jednorazowy odczyt pliku... To potrwa ok. 30-60 sek.")

    for event, elem in context:
        if elem.tag == "Record":
            long_type = elem.get("type")

            # 3. Jeśli ten typ jest w naszym słowniku krótkich nazw
            if long_type in mapping:
                short_name = mapping[long_type]

                # Wyciągamy dane do słownika (lekki format)
                record = {
                    'value': elem.get('value'),
                    'unit': elem.get('unit'),
                    'sourceName': elem.get('sourceName'),
                    'startDate': elem.get('startDate'),
                    'endDate': elem.get('endDate'),

                }

                for child in elem:
                    if child.tag == "MetadataEntry":
                        record[child.get('key')] = child.get('value')

                data_buckets[short_name].append(record)

            elem.clear()



        root = context.root

    # 4. Zamieniamy listy na DataFrames i naprawiamy typy
    final_dfs = {}
    print("📊 Konwertuję dane na tabele...")

    for short_name, records in data_buckets.items():
        if records: # Tworzymy DF tylko jeśli są dane
            df = pd.DataFrame(records)

            # Automatyczna konwersja na liczby i daty
            if 'value' in df.columns:
                df['value'] = pd.to_numeric(df['value'], errors='coerce')
            if 'startDate' in df.columns:
                df['startDate'] = pd.to_datetime(df['startDate'])
            if 'endDate' in df.columns:
                df['endDate'] = pd.to_datetime(df['endDate'])

            final_dfs[short_name] = df

    print("✅ Wszystkie dane wczytane!")
    return final_dfs



hd = load_all_health_data("eksport.xml", short_names)


df = hd.get('hr')
df.head()
df.describe()
df_steps = hd.get('steps')

🚀 Rozpoczynam jednorazowy odczyt pliku... To potrwa ok. 30-60 sek.
📊 Konwertuję dane na tabele...
✅ Wszystkie dane wczytane!

In [92]:
print(df.head())
print(df.describe())
print(df_steps.head())

   value       unit sourceName                 startDate  \
0   72.0  count/min  Zepp Life 2021-12-17 00:00:00+01:00
1   70.0  count/min  Zepp Life 2021-12-17 00:01:00+01:00
2   70.0  count/min  Zepp Life 2021-12-17 00:02:00+01:00
3   69.0  count/min  Zepp Life 2021-12-17 00:03:00+01:00
4   70.0  count/min  Zepp Life 2021-12-17 00:04:00+01:00

                    endDate HKMetadataKeyHeartRateMotionContext  \
0 2021-12-17 00:00:59+01:00                                 NaN
1 2021-12-17 00:01:59+01:00                                 NaN
2 2021-12-17 00:02:59+01:00                                 NaN
3 2021-12-17 00:03:59+01:00                                 NaN
4 2021-12-17 00:04:59+01:00                                 NaN

  HKMetadataKeySyncVersion HKMetadataKeySyncIdentifier
0                      NaN                         NaN
1                      NaN                         NaN
2                      NaN                         NaN
3                      NaN                         NaN
4                      NaN                         NaN
               value
count  401424.000000
mean       93.833004
std        28.793636
min        40.000000
25%        72.000000
50%        84.000000
75%       111.000000
max       195.000000
   value   unit sourceName                 startDate  \
0     12  count     iPhone 2020-07-29 09:39:19+01:00
1     13  count     iPhone 2020-07-29 09:56:15+01:00
2     18  count     iPhone 2020-07-29 11:38:21+01:00
3     14  count     iPhone 2020-07-29 11:49:03+01:00
4     12  count     iPhone 2020-07-29 15:47:45+01:00

                    endDate HKWasUserEntered
0 2020-07-29 09:46:55+01:00              NaN
1 2020-07-29 09:56:18+01:00              NaN
2 2020-07-29 11:38:24+01:00              NaN
3 2020-07-29 11:49:11+01:00              NaN
4 2020-07-29 15:47:48+01:00              NaN

Czyścimy  dane - usuwamy kolumny w których wszystkie wartości sa nan

In [93]:
for name, df in hd.items():
    # axis=1 oznacza kolumny, how='all' tylko te całkiem puste
    hd[name] = df.dropna(axis=1, how='all')

In [94]:
for name in hd:
    hd[name].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   value       1 non-null      int64
 1   unit        1 non-null      object
 2   sourceName  1 non-null      object
 3   startDate   1 non-null      datetime64[ns, UTC+01:00]
 4   endDate     1 non-null      datetime64[ns, UTC+01:00]
dtypes: datetime64[ns, UTC+01:00](2), int64(1), object(2)
memory usage: 172.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   value             7 non-null      float64
 1   unit              7 non-null      object
 2   sourceName        7 non-null      object
 3   startDate         7 non-null      datetime64[ns, UTC+01:00]
 4   endDate           7 non-null      datetime64[ns, UTC+01:00]
 5   HKWasUserEntered  1 non-null      object
 6   HKExternalUUID    1 non-null      object
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(4)
memory usage: 524.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   value       1 non-null      int64
 1   unit        1 non-null      object
 2   sourceName  1 non-null      object
 3   startDate   1 non-null      datetime64[ns, UTC+01:00]
 4   endDate     1 non-null      datetime64[ns, UTC+01:00]
dtypes: datetime64[ns, UTC+01:00](2), int64(1), object(2)
memory usage: 172.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   value       1 non-null      int64
 1   unit        1 non-null      object
 2   sourceName  1 non-null      object
 3   startDate   1 non-null      datetime64[ns, UTC+01:00]
 4   endDate     1 non-null      datetime64[ns, UTC+01:00]
dtypes: datetime64[ns, UTC+01:00](2), int64(1), object(2)
memory usage: 172.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401424 entries, 0 to 401423
Data columns (total 8 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   value                                401424 non-null  float64
 1   unit                                 401424 non-null  object
 2   sourceName                           401424 non-null  object
 3   startDate                            401424 non-null  datetime64[ns, UTC+01:00]
 4   endDate                              401424 non-null  datetime64[ns, UTC+01:00]
 5   HKMetadataKeyHeartRateMotionContext  278951 non-null  object
 6   HKMetadataKeySyncVersion             343 non-null     object
 7   HKMetadataKeySyncIdentifier          343 non-null     object
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(5)
memory usage: 24.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 672 entries, 0 to 671
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   value                        672 non-null    int64
 1   unit                         672 non-null    object
 2   sourceName                   672 non-null    object
 3   startDate                    672 non-null    datetime64[ns, UTC+01:00]
 4   endDate                      672 non-null    datetime64[ns, UTC+01:00]
 5   HKMetadataKeySyncVersion     1 non-null      object
 6   HKMetadataKeySyncIdentifier  1 non-null      object
dtypes: datetime64[ns, UTC+01:00](2), int64(1), object(4)
memory usage: 36.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 565 entries, 0 to 564
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   value       565 non-null    float64
 1   unit        565 non-null    object
 2   sourceName  565 non-null    object
 3   startDate   565 non-null    datetime64[ns, UTC+01:00]
 4   endDate     565 non-null    datetime64[ns, UTC+01:00]
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(2)
memory usage: 22.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   value               3282 non-null   float64
 1   unit                3282 non-null   object
 2   sourceName          3282 non-null   object
 3   startDate           3282 non-null   datetime64[ns, UTC+01:00]
 4   endDate             3282 non-null   datetime64[ns, UTC+01:00]
 5   HKAlgorithmVersion  3282 non-null   object
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(3)
memory usage: 154.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 12 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   value                                                       56 non-null     float64
 1   unit                                                        56 non-null     object
 2   sourceName                                                  56 non-null     object
 3   startDate                                                   56 non-null     datetime64[ns, UTC+01:00]
 4   endDate                                                     56 non-null     datetime64[ns, UTC+01:00]
 5   HKMetadataKeyUserMotionContext                              56 non-null     object
 6   HKMetadataKeySessionEstimate                                32 non-null     object
 7   HKMetadataKeyHeartRateRecoveryActivityDuration              56 non-null     object
 8   HKMetadataKeyHeartRateRecoveryTestType                      56 non-null     object
 9   HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate  55 non-null     object
 10  HKAlgorithmVersion                                          56 non-null     object
 11  HKMetadataKeyHeartRateRecoveryActivityType                  56 non-null     object
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(9)
memory usage: 5.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   sourceName                 1 non-null      object
 1   startDate                  1 non-null      datetime64[ns, UTC+01:00]
 2   endDate                    1 non-null      datetime64[ns, UTC+01:00]
 3   HKHeartRateEventThreshold  1 non-null      object
dtypes: datetime64[ns, UTC+01:00](2), object(2)
memory usage: 164.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100554 entries, 0 to 100553
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   value             100554 non-null  int64
 1   unit              100554 non-null  object
 2   sourceName        100554 non-null  object
 3   startDate         100554 non-null  datetime64[ns, UTC+01:00]
 4   endDate           100554 non-null  datetime64[ns, UTC+01:00]
 5   HKWasUserEntered  7 non-null       object
dtypes: datetime64[ns, UTC+01:00](2), int64(1), object(3)
memory usage: 4.6+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147294 entries, 0 to 147293
Data columns (total 7 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   value                        147294 non-null  float64
 1   unit                         147294 non-null  object
 2   sourceName                   147294 non-null  object
 3   startDate                    147294 non-null  datetime64[ns, UTC+01:00]
 4   endDate                      147294 non-null  datetime64[ns, UTC+01:00]
 5   HKMetadataKeySyncVersion     376 non-null     object
 6   HKMetadataKeySyncIdentifier  376 non-null     object
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(4)
memory usage: 7.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 619 entries, 0 to 618
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   value                        619 non-null    float64
 1   unit                         619 non-null    object
 2   sourceName                   619 non-null    object
 3   startDate                    619 non-null    datetime64[ns, UTC+01:00]
 4   endDate                      619 non-null    datetime64[ns, UTC+01:00]
 5   HKMetadataKeySyncVersion     55 non-null     object
 6   HKMetadataKeySyncIdentifier  55 non-null     object
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(4)
memory usage: 34.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 259561 entries, 0 to 259560
Data columns (total 7 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   value                        259561 non-null  float64
 1   unit                         259561 non-null  object
 2   sourceName                   259561 non-null  object
 3   startDate                    259561 non-null  datetime64[ns, UTC+01:00]
 4   endDate                      259561 non-null  datetime64[ns, UTC+01:00]
 5   HKMetadataKeySyncVersion     684 non-null     object
 6   HKMetadataKeySyncIdentifier  684 non-null     object
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(4)
memory usage: 13.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 274265 entries, 0 to 274264
Data columns (total 7 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   value                        274265 non-null  float64
 1   unit                         274265 non-null  object
 2   sourceName                   274265 non-null  object
 3   startDate                    274265 non-null  datetime64[ns, UTC+01:00]
 4   endDate                      274265 non-null  datetime64[ns, UTC+01:00]
 5   HKMetadataKeySyncVersion     683 non-null     object
 6   HKMetadataKeySyncIdentifier  683 non-null     object
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(4)
memory usage: 14.6+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3584 entries, 0 to 3583
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   value       3584 non-null   int64
 1   unit        3584 non-null   object
 2   sourceName  3584 non-null   object
 3   startDate   3584 non-null   datetime64[ns, UTC+01:00]
 4   endDate     3584 non-null   datetime64[ns, UTC+01:00]
dtypes: datetime64[ns, UTC+01:00](2), int64(1), object(2)
memory usage: 140.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24668 entries, 0 to 24667
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   value       24668 non-null  int64
 1   unit        24668 non-null  object
 2   sourceName  24668 non-null  object
 3   startDate   24668 non-null  datetime64[ns, UTC+01:00]
 4   endDate     24668 non-null  datetime64[ns, UTC+01:00]
dtypes: datetime64[ns, UTC+01:00](2), int64(1), object(2)
memory usage: 963.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23922 entries, 0 to 23921
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   value       23922 non-null  int64
 1   unit        23922 non-null  object
 2   sourceName  23922 non-null  object
 3   startDate   23922 non-null  datetime64[ns, UTC+01:00]
 4   endDate     23922 non-null  datetime64[ns, UTC+01:00]
dtypes: datetime64[ns, UTC+01:00](2), int64(1), object(2)
memory usage: 934.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sourceName  16000 non-null  object
 1   startDate   16000 non-null  datetime64[ns, UTC+01:00]
 2   endDate     16000 non-null  datetime64[ns, UTC+01:00]
dtypes: datetime64[ns, UTC+01:00](2), object(1)
memory usage: 375.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213221 entries, 0 to 213220
Data columns (total 9 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   value                           213221 non-null  float64
 1   unit                            213221 non-null  object
 2   sourceName                      213221 non-null  object
 3   startDate                       213221 non-null  datetime64[ns, UTC+01:00]
 4   endDate                         213221 non-null  datetime64[ns, UTC+01:00]
 5   HKActivityType                  213221 non-null  object
 6   HKAlgorithmVersion              213221 non-null  object
 7   HKPhysicalEffortEstimationType  213221 non-null  object
 8   HKIndoorWorkout                 1475 non-null    object
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(6)
memory usage: 14.6+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   value                        173 non-null    float64
 1   unit                         173 non-null    object
 2   sourceName                   173 non-null    object
 3   startDate                    173 non-null    datetime64[ns, UTC+01:00]
 4   endDate                      173 non-null    datetime64[ns, UTC+01:00]
 5   HKVO2MaxTestType             173 non-null    object
 6   HKMetadataKeySyncVersion     173 non-null    object
 7   HKMetadataKeySyncIdentifier  173 non-null    object
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(5)
memory usage: 10.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39469 entries, 0 to 39468
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   value       39469 non-null  float64
 1   unit        39469 non-null  object
 2   sourceName  39469 non-null  object
 3   startDate   39469 non-null  datetime64[ns, UTC+01:00]
 4   endDate     39469 non-null  datetime64[ns, UTC+01:00]
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(2)
memory usage: 1.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39467 entries, 0 to 39466
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   value       39467 non-null  int64
 1   unit        39467 non-null  object
 2   sourceName  39467 non-null  object
 3   startDate   39467 non-null  datetime64[ns, UTC+01:00]
 4   endDate     39467 non-null  datetime64[ns, UTC+01:00]
dtypes: datetime64[ns, UTC+01:00](2), int64(1), object(2)
memory usage: 1.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23671 entries, 0 to 23670
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   value                             23671 non-null  float64
 1   unit                              23671 non-null  object
 2   sourceName                        23671 non-null  object
 3   startDate                         23671 non-null  datetime64[ns, UTC+01:00]
 4   endDate                           23671 non-null  datetime64[ns, UTC+01:00]
 5   HKMetadataKeyDevicePlacementSide  23671 non-null  object
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(3)
memory usage: 1.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36523 entries, 0 to 36522
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   value       36523 non-null  float64
 1   unit        36523 non-null  object
 2   sourceName  36523 non-null  object
 3   startDate   36523 non-null  datetime64[ns, UTC+01:00]
 4   endDate     36523 non-null  datetime64[ns, UTC+01:00]
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(2)
memory usage: 1.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1284 entries, 0 to 1283
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   value       1284 non-null   float64
 1   unit        1284 non-null   object
 2   sourceName  1284 non-null   object
 3   startDate   1284 non-null   datetime64[ns, UTC+01:00]
 4   endDate     1284 non-null   datetime64[ns, UTC+01:00]
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(2)
memory usage: 50.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1849 entries, 0 to 1848
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   value       1849 non-null   float64
 1   unit        1849 non-null   object
 2   sourceName  1849 non-null   object
 3   startDate   1849 non-null   datetime64[ns, UTC+01:00]
 4   endDate     1849 non-null   datetime64[ns, UTC+01:00]
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(2)
memory usage: 72.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   value               161 non-null    float64
 1   unit                161 non-null    object
 2   sourceName          161 non-null    object
 3   startDate           161 non-null    datetime64[ns, UTC+01:00]
 4   endDate             161 non-null    datetime64[ns, UTC+01:00]
 5   HKAlgorithmVersion  116 non-null    object
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(3)
memory usage: 7.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 7 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   value                                71 non-null     int64
 1   unit                                 71 non-null     object
 2   sourceName                           71 non-null     object
 3   startDate                            71 non-null     datetime64[ns, UTC+01:00]
 4   endDate                              71 non-null     datetime64[ns, UTC+01:00]
 5   HKDateOfEarliestDataUsedForEstimate  71 non-null     object
 6   HKMetadataKeyAppleDeviceCalibrated   71 non-null     object
dtypes: datetime64[ns, UTC+01:00](2), int64(1), object(4)
memory usage: 4.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10507 entries, 0 to 10506
Data columns (total 6 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   value                            10507 non-null  float64
 1   unit                             10507 non-null  object
 2   sourceName                       10507 non-null  object
 3   startDate                        10507 non-null  datetime64[ns, UTC+01:00]
 4   endDate                          10507 non-null  datetime64[ns, UTC+01:00]
 5   HKMetadataKeyBarometricPressure  10507 non-null  object
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(3)
memory usage: 492.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35457 entries, 0 to 35456
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   value       35457 non-null  float64
 1   unit        35457 non-null  object
 2   sourceName  35457 non-null  object
 3   startDate   35457 non-null  datetime64[ns, UTC+01:00]
 4   endDate     35457 non-null  datetime64[ns, UTC+01:00]
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(2)
memory usage: 1.4+ MB

In [125]:
hd['hr'].info()
print(hd['hr'].describe())
print(hd['hr'].tail(20))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401424 entries, 0 to 401423
Data columns (total 6 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   value                                401424 non-null  float64
 1   unit                                 401424 non-null  object
 2   sourceName                           401424 non-null  object
 3   startDate                            401424 non-null  datetime64[ns, UTC+01:00]
 4   endDate                              401424 non-null  datetime64[ns, UTC+01:00]
 5   HKMetadataKeyHeartRateMotionContext  278951 non-null  object
dtypes: datetime64[ns, UTC+01:00](2), float64(1), object(3)
memory usage: 18.4+ MB
               value
count  401424.000000
mean       93.833004
std        28.793636
min        40.000000
25%        72.000000
50%        84.000000
75%       111.000000
max       195.000000
        value       unit         sourceName                 startDate  \
401404   95.0  count/min  Apple Watch (Lol) 2026-03-05 14:38:07+01:00
401405   93.0  count/min  Apple Watch (Lol) 2026-03-05 14:38:12+01:00
401406   87.0  count/min  Apple Watch (Lol) 2026-03-05 14:38:21+01:00
401407   87.0  count/min  Apple Watch (Lol) 2026-03-05 14:38:26+01:00
401408   86.0  count/min  Apple Watch (Lol) 2026-03-05 14:38:30+01:00
401409   88.0  count/min  Apple Watch (Lol) 2026-03-05 14:38:33+01:00
401410   87.0  count/min  Apple Watch (Lol) 2026-03-05 14:38:37+01:00
401411   93.0  count/min  Apple Watch (Lol) 2026-03-05 14:38:42+01:00
401412   96.0  count/min  Apple Watch (Lol) 2026-03-05 14:38:47+01:00
401413   89.0  count/min  Apple Watch (Lol) 2026-03-05 14:38:54+01:00
401414   86.0  count/min  Apple Watch (Lol) 2026-03-05 14:39:01+01:00
401415   86.0  count/min  Apple Watch (Lol) 2026-03-05 14:39:05+01:00
401416   87.0  count/min  Apple Watch (Lol) 2026-03-05 14:39:07+01:00
401417   92.0  count/min  Apple Watch (Lol) 2026-03-05 14:39:12+01:00
401418  107.0  count/min  Apple Watch (Lol) 2026-03-05 14:39:21+01:00
401419  107.0  count/min  Apple Watch (Lol) 2026-03-05 14:39:22+01:00
401420  107.0  count/min  Apple Watch (Lol) 2026-03-05 14:39:27+01:00
401421  101.0  count/min  Apple Watch (Lol) 2026-03-05 14:39:32+01:00
401422  107.0  count/min  Apple Watch (Lol) 2026-03-05 14:39:56+01:00
401423   83.0  count/min  Apple Watch (Lol) 2026-03-05 15:00:28+01:00

                         endDate HKMetadataKeyHeartRateMotionContext
401404 2026-03-05 14:38:07+01:00                                   2
401405 2026-03-05 14:38:12+01:00                                   2
401406 2026-03-05 14:38:21+01:00                                   2
401407 2026-03-05 14:38:26+01:00                                   2
401408 2026-03-05 14:38:30+01:00                                   2
401409 2026-03-05 14:38:33+01:00                                   2
401410 2026-03-05 14:38:37+01:00                                   2
401411 2026-03-05 14:38:42+01:00                                   2
401412 2026-03-05 14:38:47+01:00                                   2
401413 2026-03-05 14:38:54+01:00                                   2
401414 2026-03-05 14:39:01+01:00                                   2
401415 2026-03-05 14:39:05+01:00                                   2
401416 2026-03-05 14:39:07+01:00                                   2
401417 2026-03-05 14:39:12+01:00                                   2
401418 2026-03-05 14:39:21+01:00                                   2
401419 2026-03-05 14:39:22+01:00                                   2
401420 2026-03-05 14:39:27+01:00                                   2
401421 2026-03-05 14:39:32+01:00                                   2
401422 2026-03-05 14:39:56+01:00                                   2
401423 2026-03-05 15:00:28+01:00                                   1

In [167]:
df = hd['hr']

,value,unit,sourceName,startDate,endDate,HKMetadataKeyHeartRateMotionContext
0,72.0,count/min,Zepp Life,2021-12-17 00:00:00+01:00,2021-12-17 00:00:59+01:00,NaN
1,70.0,count/min,Zepp Life,2021-12-17 00:01:00+01:00,2021-12-17 00:01:59+01:00,NaN
2,70.0,count/min,Zepp Life,2021-12-17 00:02:00+01:00,2021-12-17 00:02:59+01:00,NaN
3,69.0,count/min,Zepp Life,2021-12-17 00:03:00+01:00,2021-12-17 00:03:59+01:00,NaN
4,70.0,count/min,Zepp Life,2021-12-17 00:04:00+01:00,2021-12-17 00:04:59+01:00,NaN
...,...,...,...,...,...,...
401419,107.0,count/min,Apple Watch (Lol),2026-03-05 14:39:22+01:00,2026-03-05 14:39:22+01:00,2
401420,107.0,count/min,Apple Watch (Lol),2026-03-05 14:39:27+01:00,2026-03-05 14:39:27+01:00,2
401421,101.0,count/min,Apple Watch (Lol),2026-03-05 14:39:32+01:00,2026-03-05 14:39:32+01:00,2
401422,107.0,count/min,Apple Watch (Lol),2026-03-05 14:39:56+01:00,2026-03-05 14:39:56+01:00,2
401423,83.0,count/min,Apple Watch (Lol),2026-03-05 15:00:28+01:00,2026-03-05 15:00:28+01:00,1

In [173]:
# Usuwamy konkretne kolumny techniczne, których nie potrzebujemy do analizy tętna
df = hd['hr'].drop(columns=['HKMetadataKeySyncVersion', 'HKMetadataKeySyncIdentifier'], errors='ignore')

In [169]:
print(df.columns)

Index(['value', 'unit', 'sourceName', 'startDate', 'endDate',
       'HKMetadataKeyHeartRateMotionContext'],
      dtype='object')

In [174]:



# Sprawdzamy, czy początek i koniec są takie same
# Wynikiem będzie True dla punktów (np. tętno) i False dla przedziałów (np. kroki)
df['is_point'] = df['startDate'] == df['endDate']

# Szybki podgląd: ile masz przedziałów, a ile punktów?
print(df['is_point'].value_counts())

is_point
True     278608
False       343
Name: count, dtype: int64

In [177]:
# Usuwamy rekordy, które mają IDENTYCZNY start, koniec I wartość
df_clean = df.drop_duplicates(subset=['startDate', 'endDate', 'value'])

print(f"Usunięto {len(df) - len(df_clean)} idealnych duplikatów.")

Usunięto 0 idealnych duplikatów.

In [178]:
df['midPoint'] = df['startDate'] + (df['endDate'] - df['startDate']) / 2

In [179]:
# Resampling dla kroków (sumujemy w oknie 1-minutowym)
df_steps_1min = df_steps.set_index('startDate')['value'].resample('1min').sum()

In [180]:
print(df.columns)

Index(['value', 'unit', 'sourceName', 'startDate', 'endDate',
       'HKMetadataKeyHeartRateMotionContext', 'is_point', 'midPoint'],
      dtype='object')

In [164]:
# 1. USUWANIE DUPLIKATÓW
# Czyścimy rekordy, które są identyczne (poczatek, koniec, wartość)
df = df.drop_duplicates(subset=['startDate', 'endDate', 'value'])

# Szukamy słowa "Apple" i ignorujemy to, co jest między wyrazami
df = df[df['sourceName'].str.contains('Apple', na=False)]


# 3. KONTROLA DATY (Inżynierskie BHP)
# Wywalamy rekordy, gdzie koniec jest przed początkiem (błędy systemowe)
df = df[df['endDate'] >= df['startDate']]

# 4. PRZYGOTOWANIE DO RESAMPLINGU
# Musimy ustawić datę jako indeks, żeby Pandas mógł "pogrupować" czas
df = df.set_index('startDate')

# 5. RESAMPLING (Ujednolicenie do 1 minuty)
# Zamiast 400k nieregularnych punktów, robimy średnią dla każdej minuty
df_hr_1min = df['value'].resample('1min').mean()

# 6. USUNIĘCIE "DZIUR" (Opcjonalnie)
# Jeśli przez godzinę nie miałaś zegarka, resampling stworzy tam NaN. Usuwamy je.
df_hr_1min = df_hr_1min.dropna()

print(f"Sukces! Twoje dane tętna są teraz jednolite. Zostało {len(df_hr_1min)} czystych minut.")

✅ Przefiltrowano dane po źródle.
Sukces! Twoje dane tętna są teraz jednolite. Zostało 168353 czystych minut.

In [165]:
display(df_hr_1min)

,value,unit,sourceName,endDate,HKMetadataKeyHeartRateMotionContext,duration,is_point,midPoint
startDate,,,,,,,,
2024-03-03 16:10:22+01:00,93.0,count/min,Apple Watch (Lol),2024-03-03 16:10:22+01:00,1,0 days,True,2024-03-03 16:10:22+01:00
2024-03-03 16:12:16+01:00,84.0,count/min,Apple Watch (Lol),2024-03-03 16:12:16+01:00,1,0 days,True,2024-03-03 16:12:16+01:00
2024-03-03 16:18:43+01:00,82.0,count/min,Apple Watch (Lol),2024-03-03 16:18:43+01:00,1,0 days,True,2024-03-03 16:18:43+01:00
2024-03-03 16:24:23+01:00,80.0,count/min,Apple Watch (Lol),2024-03-03 16:24:23+01:00,1,0 days,True,2024-03-03 16:24:23+01:00
2024-03-03 16:25:28+01:00,78.0,count/min,Apple Watch (Lol),2024-03-03 16:25:28+01:00,1,0 days,True,2024-03-03 16:25:28+01:00
...,...,...,...,...,...,...,...,...
2026-03-05 14:39:22+01:00,107.0,count/min,Apple Watch (Lol),2026-03-05 14:39:22+01:00,2,0 days,True,2026-03-05 14:39:22+01:00
2026-03-05 14:39:27+01:00,107.0,count/min,Apple Watch (Lol),2026-03-05 14:39:27+01:00,2,0 days,True,2026-03-05 14:39:27+01:00
2026-03-05 14:39:32+01:00,101.0,count/min,Apple Watch (Lol),2026-03-05 14:39:32+01:00,2,0 days,True,2026-03-05 14:39:32+01:00
2026-03-05 14:39:56+01:00,107.0,count/min,Apple Watch (Lol),2026-03-05 14:39:56+01:00,2,0 days,True,2026-03-05 14:39:56+01:00
2026-03-05 15:00:28+01:00,83.0,count/min,Apple Watch (Lol),2026-03-05 15:00:28+01:00,1,0 days,True,2026-03-05 15:00:28+01:00