# ANALIZA DANYCH Z ZEGARKA APPLE WATCH


## Podstawowe informacje o pliku:

* Plik jest pobierany z aplikacji Zdrowie (Apple Health) na telefonie
* format: XML
* struktura: hierarchiczna, z wieloma różnymi typami rekordów (Record, Correlation, Workout, ActivitySummary, ClinicalRecord, Audiogram, VisionPrescription)
* zawiera dane dotyczące zdrowia, aktywności, snu, tętna, kroków, itp.
* jest dość duży ponad 700 mb

## TO DO:
1. [x] rozgryźć strukturę pliku xml - pól w nim zawartych - co dokładnie w nim jest
2. [x] sprawdzić pomiar EKG i możliwość ściągnięcia danych
3. [x] napisać kod pythona do wczytania tych danych
4. [x] zastanowić się nad programem ćwiczeń dla osób o różnej kondycji, z pomiarem zegarkiem

In [9]:
import os
import streamlit as st
import time

from altair.datasets import data
from lxml import etree as ET
import pandas as pd
from parser import load_one_type, load_all_health_data

In [10]:
path = "06-04/apple_health_export/eksport.xml"

In [11]:
def discover_xml_structure(file_path):
    # Słownik: Klucz = Nazwa Tagu, Wartość = Zbiór atrybutów 'type' lub 'workoutActivityType'
    found_structures = {}

    context = ET.iterparse(file_path, events=("end",))

    for event, elem in context:
        tag_name = elem.tag

        #  dodajemy do slownika jesli nie ma w nim jeszcze
        if tag_name not in found_structures:
            found_structures[tag_name] = set()

        # sprawdzamy typy głównych tagów
        sub_type = elem.get("type") or elem.get("workoutActivityType") or "Brak"

        found_structures[tag_name].add(sub_type)

        # Czyścimy RAM
        elem.clear()

    return found_structures

moje_dane = discover_xml_structure(path)

print("ODKRYTE TAGI + typy danych")
for tag, sub_types in moje_dane.items():
    print(f"\n TAG: <{tag}>")
    print(f"   Liczba różnych typów: {len(sub_types)}")
    for st in list(sub_types):
        print(f"     - {st}")

ODKRYTE TAGI + typy danych

 TAG: <ExportDate>
   Liczba różnych typów: 1
     - Brak

 TAG: <Me>
   Liczba różnych typów: 1
     - Brak

 TAG: <Record>
   Liczba różnych typów: 41
     - HKQuantityTypeIdentifierRespiratoryRate
     - HKQuantityTypeIdentifierWalkingDoubleSupportPercentage
     - HKCategoryTypeIdentifierSleepAnalysis
     - HKQuantityTypeIdentifierHeadphoneAudioExposure
     - HKQuantityTypeIdentifierBodyFatPercentage
     - HKQuantityTypeIdentifierEnvironmentalSoundReduction
     - HKQuantityTypeIdentifierStairDescentSpeed
     - HKQuantityTypeIdentifierOxygenSaturation
     - HKQuantityTypeIdentifierAppleExerciseTime
     - HKQuantityTypeIdentifierWalkingAsymmetryPercentage
     - HKDataTypeSleepDurationGoal
     - HKQuantityTypeIdentifierHeight
     - HKQuantityTypeIdentifierAppleWalkingSteadiness
     - HKQuantityTypeIdentifierAppleSleepingWristTemperature
     - HKQuantityTypeIdentifierHeartRateRecoveryOneMinute
     - HKCategoryTypeIdentifierAudioExposureEvent
     - HKQuantityTypeIdentifierWalkingHeartRateAverage
     - HKQuantityTypeIdentifierEnvironmentalAudioExposure
     - HKQuantityTypeIdentifierDistanceCycling
     - HKQuantityTypeIdentifierSixMinuteWalkTestDistance
     - HKCategoryTypeIdentifierHighHeartRateEvent
     - HKQuantityTypeIdentifierHeartRate
     - HKQuantityTypeIdentifierStepCount
     - HKQuantityTypeIdentifierBodyMass
     - HKQuantityTypeIdentifierVO2Max
     - HKQuantityTypeIdentifierTimeInDaylight
     - HKQuantityTypeIdentifierRestingHeartRate
     - HKQuantityTypeIdentifierFlightsClimbed
     - HKCategoryTypeIdentifierMenstrualFlow
     - HKQuantityTypeIdentifierHeartRateVariabilitySDNN
     - HKQuantityTypeIdentifierWaistCircumference
     - HKQuantityTypeIdentifierBasalEnergyBurned
     - HKQuantityTypeIdentifierDistanceWalkingRunning
     - HKCategoryTypeIdentifierAppleStandHour
     - HKCategoryTypeIdentifierHeadphoneAudioExposureEvent
     - HKQuantityTypeIdentifierStairAscentSpeed
     - HKQuantityTypeIdentifierWalkingStepLength
     - HKQuantityTypeIdentifierActiveEnergyBurned
     - HKQuantityTypeIdentifierAppleStandTime
     - HKQuantityTypeIdentifierPhysicalEffort
     - HKQuantityTypeIdentifierWalkingSpeed

 TAG: <MetadataEntry>
   Liczba różnych typów: 1
     - Brak

 TAG: <WorkoutEvent>
   Liczba różnych typów: 4
     - HKWorkoutEventTypeSegment
     - HKWorkoutEventTypeMarker
     - HKWorkoutEventTypePause
     - HKWorkoutEventTypeResume

 TAG: <WorkoutStatistics>
   Liczba różnych typów: 5
     - HKQuantityTypeIdentifierDistanceWalkingRunning
     - HKQuantityTypeIdentifierHeartRate
     - HKQuantityTypeIdentifierActiveEnergyBurned
     - HKQuantityTypeIdentifierDistanceCycling
     - HKQuantityTypeIdentifierBasalEnergyBurned

 TAG: <Workout>
   Liczba różnych typów: 8
     - HKWorkoutActivityTypeWalking
     - HKWorkoutActivityTypeElliptical
     - HKWorkoutActivityTypeTennis
     - HKWorkoutActivityTypePilates
     - HKWorkoutActivityTypeCycling
     - HKWorkoutActivityTypeFunctionalStrengthTraining
     - HKWorkoutActivityTypeStairClimbing
     - HKWorkoutActivityTypeCardioDance

 TAG: <FileReference>
   Liczba różnych typów: 1
     - Brak

 TAG: <WorkoutRoute>
   Liczba różnych typów: 1
     - Brak

 TAG: <ActivitySummary>
   Liczba różnych typów: 1
     - Brak

 TAG: <InstantaneousBeatsPerMinute>
   Liczba różnych typów: 1
     - Brak

 TAG: <HeartRateVariabilityMetadataList>
   Liczba różnych typów: 1
     - Brak

 TAG: <HealthData>
   Liczba różnych typów: 1
     - Brak

In [12]:
important_tags = {
    'Me',"Record", "Workout", "ActivitySummary", "InstantaneousBeatsPerMinute"
}

In [13]:
print(moje_dane)

{'ExportDate': {'Brak'}, 'Me': {'Brak'}, 'Record': {'HKQuantityTypeIdentifierRespiratoryRate', 'HKQuantityTypeIdentifierWalkingDoubleSupportPercentage', 'HKCategoryTypeIdentifierSleepAnalysis', 'HKQuantityTypeIdentifierHeadphoneAudioExposure', 'HKQuantityTypeIdentifierBodyFatPercentage', 'HKQuantityTypeIdentifierEnvironmentalSoundReduction', 'HKQuantityTypeIdentifierStairDescentSpeed', 'HKQuantityTypeIdentifierOxygenSaturation', 'HKQuantityTypeIdentifierAppleExerciseTime', 'HKQuantityTypeIdentifierWalkingAsymmetryPercentage', 'HKDataTypeSleepDurationGoal', 'HKQuantityTypeIdentifierHeight', 'HKQuantityTypeIdentifierAppleWalkingSteadiness', 'HKQuantityTypeIdentifierAppleSleepingWristTemperature', 'HKQuantityTypeIdentifierHeartRateRecoveryOneMinute', 'HKCategoryTypeIdentifierAudioExposureEvent', 'HKQuantityTypeIdentifierWalkingHeartRateAverage', 'HKQuantityTypeIdentifierEnvironmentalAudioExposure', 'HKQuantityTypeIdentifierDistanceCycling', 'HKQuantityTypeIdentifierSixMinuteWalkTestDistance', 'HKCategoryTypeIdentifierHighHeartRateEvent', 'HKQuantityTypeIdentifierHeartRate', 'HKQuantityTypeIdentifierStepCount', 'HKQuantityTypeIdentifierBodyMass', 'HKQuantityTypeIdentifierVO2Max', 'HKQuantityTypeIdentifierTimeInDaylight', 'HKQuantityTypeIdentifierRestingHeartRate', 'HKQuantityTypeIdentifierFlightsClimbed', 'HKCategoryTypeIdentifierMenstrualFlow', 'HKQuantityTypeIdentifierHeartRateVariabilitySDNN', 'HKQuantityTypeIdentifierWaistCircumference', 'HKQuantityTypeIdentifierBasalEnergyBurned', 'HKQuantityTypeIdentifierDistanceWalkingRunning', 'HKCategoryTypeIdentifierAppleStandHour', 'HKCategoryTypeIdentifierHeadphoneAudioExposureEvent', 'HKQuantityTypeIdentifierStairAscentSpeed', 'HKQuantityTypeIdentifierWalkingStepLength', 'HKQuantityTypeIdentifierActiveEnergyBurned', 'HKQuantityTypeIdentifierAppleStandTime', 'HKQuantityTypeIdentifierPhysicalEffort', 'HKQuantityTypeIdentifierWalkingSpeed'}, 'MetadataEntry': {'Brak'}, 'WorkoutEvent': {'HKWorkoutEventTypeSegment', 'HKWorkoutEventTypeMarker', 'HKWorkoutEventTypePause', 'HKWorkoutEventTypeResume'}, 'WorkoutStatistics': {'HKQuantityTypeIdentifierDistanceWalkingRunning', 'HKQuantityTypeIdentifierHeartRate', 'HKQuantityTypeIdentifierActiveEnergyBurned', 'HKQuantityTypeIdentifierDistanceCycling', 'HKQuantityTypeIdentifierBasalEnergyBurned'}, 'Workout': {'HKWorkoutActivityTypeWalking', 'HKWorkoutActivityTypeElliptical', 'HKWorkoutActivityTypeTennis', 'HKWorkoutActivityTypePilates', 'HKWorkoutActivityTypeCycling', 'HKWorkoutActivityTypeFunctionalStrengthTraining', 'HKWorkoutActivityTypeStairClimbing', 'HKWorkoutActivityTypeCardioDance'}, 'FileReference': {'Brak'}, 'WorkoutRoute': {'Brak'}, 'ActivitySummary': {'Brak'}, 'InstantaneousBeatsPerMinute': {'Brak'}, 'HeartRateVariabilityMetadataList': {'Brak'}, 'HealthData': {'Brak'}}

In [14]:

diff_types = set()

diff_tags = set()
# Iterujemy po pliku
for event, elem in ET.iterparse(path, events=("end",)):
    if elem.tag in important_tags:
        typ = elem.get("type")  or elem.get("workoutActivityType") or elem.tag

        if typ not in diff_types:
            print(f"\n TYP: {typ}")
            print(f"   Atrybuty: {elem.attrib}")


            children = list(elem)
            if children:
                for child in children:
                    print(f"   typ: <{child.tag}> atrybuty: {child.attrib}")
            diff_types.add(typ)



        elem.clear()

 TYP: Me
   Atrybuty: {'HKCharacteristicTypeIdentifierDateOfBirth': '2006-03-02', 'HKCharacteristicTypeIdentifierBiologicalSex': 'HKBiologicalSexFemale', 'HKCharacteristicTypeIdentifierBloodType': 'HKBloodTypeNotSet', 'HKCharacteristicTypeIdentifierFitzpatrickSkinType': 'HKFitzpatrickSkinTypeNotSet', 'HKCharacteristicTypeIdentifierCardioFitnessMedicationsUse': 'Brak'}

 TYP: HKQuantityTypeIdentifierHeight
   Atrybuty: {'type': 'HKQuantityTypeIdentifierHeight', 'sourceName': 'FitnessOnline', 'sourceVersion': '206', 'unit': 'cm', 'creationDate': '2025-08-12 12:58:06 +0200', 'startDate': '2025-08-12 12:58:05 +0200', 'endDate': '2025-08-12 12:58:05 +0200', 'value': '163'}

 TYP: HKQuantityTypeIdentifierBodyMass
   Atrybuty: {'type': 'HKQuantityTypeIdentifierBodyMass', 'sourceName': 'Zdrowie', 'sourceVersion': '14.7.1', 'unit': 'kg', 'creationDate': '2021-09-06 11:46:43 +0200', 'startDate': '2021-09-06 11:46:00 +0200', 'endDate': '2021-09-06 11:46:00 +0200', 'value': '55'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKWasUserEntered', 'value': '1'}

 TYP: HKQuantityTypeIdentifierHeartRate
   Atrybuty: {'type': 'HKQuantityTypeIdentifierHeartRate', 'sourceName': 'Zepp Life', 'sourceVersion': '202112101619', 'unit': 'count/min', 'creationDate': '2021-12-24 17:29:14 +0200', 'startDate': '2021-12-17 01:00:00 +0200', 'endDate': '2021-12-17 01:00:59 +0200', 'value': '72'}

 TYP: HKQuantityTypeIdentifierOxygenSaturation
   Atrybuty: {'type': 'HKQuantityTypeIdentifierOxygenSaturation', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0xab1023bb0>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': '%', 'creationDate': '2024-03-03 20:36:47 +0200', 'startDate': '2024-03-03 20:36:47 +0200', 'endDate': '2024-03-03 20:36:47 +0200', 'value': '0.99'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyBarometricPressure', 'value': '99.7209 kPa'}

 TYP: HKQuantityTypeIdentifierRespiratoryRate
   Atrybuty: {'type': 'HKQuantityTypeIdentifierRespiratoryRate', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0xab1020f00>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': 'count/min', 'creationDate': '2024-03-03 22:40:34 +0200', 'startDate': '2024-03-03 22:37:30 +0200', 'endDate': '2024-03-03 22:37:30 +0200', 'value': '21'}

 TYP: HKQuantityTypeIdentifierBodyFatPercentage
   Atrybuty: {'type': 'HKQuantityTypeIdentifierBodyFatPercentage', 'sourceName': 'FitnessOnline', 'sourceVersion': '206', 'unit': '%', 'creationDate': '2025-08-12 12:58:06 +0200', 'startDate': '2025-08-12 12:58:05 +0200', 'endDate': '2025-08-12 12:58:05 +0200', 'value': '0'}

 TYP: HKQuantityTypeIdentifierStepCount
   Atrybuty: {'type': 'HKQuantityTypeIdentifierStepCount', 'sourceName': 'iPhone', 'sourceVersion': '13.6', 'device': '<<HKDevice: 0xab346b520>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:13.6, creation date:2020-07-29 09:04:05 +0000>', 'unit': 'count', 'creationDate': '2020-07-29 11:04:05 +0200', 'startDate': '2020-07-29 10:39:19 +0200', 'endDate': '2020-07-29 10:46:55 +0200', 'value': '12'}

 TYP: HKQuantityTypeIdentifierDistanceWalkingRunning
   Atrybuty: {'type': 'HKQuantityTypeIdentifierDistanceWalkingRunning', 'sourceName': 'iPhone', 'sourceVersion': '13.6', 'device': '<<HKDevice: 0xab1023f20>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:13.6, creation date:2020-07-29 09:04:05 +0000>', 'unit': 'km', 'creationDate': '2020-07-29 11:04:05 +0200', 'startDate': '2020-07-29 10:39:19 +0200', 'endDate': '2020-07-29 10:46:55 +0200', 'value': '0.00712'}

 TYP: HKQuantityTypeIdentifierBasalEnergyBurned
   Atrybuty: {'type': 'HKQuantityTypeIdentifierBasalEnergyBurned', 'sourceName': 'iPhone', 'sourceVersion': '16.0', 'device': '<<HKDevice: 0xab1022d50>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:16.0, creation date:2022-09-13 20:34:48 +0000>', 'unit': 'kcal', 'creationDate': '2022-09-13 22:34:48 +0200', 'startDate': '2022-09-12 22:35:44 +0200', 'endDate': '2022-09-12 22:50:39 +0200', 'value': '13.153'}

 TYP: HKQuantityTypeIdentifierActiveEnergyBurned
   Atrybuty: {'type': 'HKQuantityTypeIdentifierActiveEnergyBurned', 'sourceName': 'Zepp Life', 'sourceVersion': '202203221509', 'unit': 'kcal', 'creationDate': '2022-05-18 22:38:17 +0200', 'startDate': '2022-02-22 08:10:00 +0200', 'endDate': '2022-02-22 08:19:59 +0200', 'value': '4'}

 TYP: HKQuantityTypeIdentifierFlightsClimbed
   Atrybuty: {'type': 'HKQuantityTypeIdentifierFlightsClimbed', 'sourceName': 'iPhone', 'sourceVersion': '13.6.1', 'device': '<<HKDevice: 0xab1022bc0>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:13.6.1, creation date:2020-08-21 16:31:18 +0000>', 'unit': 'count', 'creationDate': '2020-08-23 14:12:47 +0200', 'startDate': '2020-08-23 14:00:22 +0200', 'endDate': '2020-08-23 14:00:25 +0200', 'value': '1'}

 TYP: HKQuantityTypeIdentifierAppleExerciseTime
   Atrybuty: {'type': 'HKQuantityTypeIdentifierAppleExerciseTime', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0xab1021590>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': 'min', 'creationDate': '2024-03-04 09:05:20 +0200', 'startDate': '2024-03-04 09:03:00 +0200', 'endDate': '2024-03-04 09:04:00 +0200', 'value': '1'}

 TYP: HKQuantityTypeIdentifierDistanceCycling
   Atrybuty: {'type': 'HKQuantityTypeIdentifierDistanceCycling', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.4', 'device': '<<HKDevice: 0xab10219a0>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.4, creation date:2024-03-23 21:29:37 +0000>', 'unit': 'km', 'creationDate': '2024-06-11 19:45:23 +0200', 'startDate': '2024-06-11 19:43:00 +0200', 'endDate': '2024-06-11 19:43:29 +0200', 'value': '0.104494'}

 TYP: HKQuantityTypeIdentifierWaistCircumference
   Atrybuty: {'type': 'HKQuantityTypeIdentifierWaistCircumference', 'sourceName': 'FitnessOnline', 'sourceVersion': '206', 'unit': 'cm', 'creationDate': '2025-08-12 12:58:06 +0200', 'startDate': '2025-08-12 12:58:05 +0200', 'endDate': '2025-08-12 12:58:05 +0200', 'value': '0'}

 TYP: HKQuantityTypeIdentifierRestingHeartRate
   Atrybuty: {'type': 'HKQuantityTypeIdentifierRestingHeartRate', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'unit': 'count/min', 'creationDate': '2024-03-03 18:56:52 +0200', 'startDate': '2024-03-03 17:10:22 +0200', 'endDate': '2024-03-03 18:55:09 +0200', 'value': '72'}

 TYP: HKQuantityTypeIdentifierVO2Max
   Atrybuty: {'type': 'HKQuantityTypeIdentifierVO2Max', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '2890.8.3', 'unit': 'mL/min·kg', 'creationDate': '2024-03-05 13:07:27 +0200', 'startDate': '2024-03-05 13:07:27 +0200', 'endDate': '2024-03-05 13:07:27 +0200', 'value': '26.31'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKVO2MaxTestType', 'value': '2'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeySyncVersion', 'value': '1'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeySyncIdentifier', 'value': '3BA9D79C-F29B-4EAF-A67E-537BC3F23BBD'}

 TYP: HKQuantityTypeIdentifierWalkingHeartRateAverage
   Atrybuty: {'type': 'HKQuantityTypeIdentifierWalkingHeartRateAverage', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3.1', 'unit': 'count/min', 'creationDate': '2024-03-05 23:29:13 +0200', 'startDate': '2024-03-04 01:00:36 +0200', 'endDate': '2024-03-05 00:56:10 +0200', 'value': '118'}

 TYP: HKQuantityTypeIdentifierEnvironmentalAudioExposure
   Atrybuty: {'type': 'HKQuantityTypeIdentifierEnvironmentalAudioExposure', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0xab1022490>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': 'dBASPL', 'creationDate': '2024-03-03 17:15:55 +0200', 'startDate': '2024-03-03 17:05:54 +0200', 'endDate': '2024-03-03 17:35:53 +0200', 'value': '69.7388'}

 TYP: HKQuantityTypeIdentifierHeadphoneAudioExposure
   Atrybuty: {'type': 'HKQuantityTypeIdentifierHeadphoneAudioExposure', 'sourceName': 'iPhone', 'sourceVersion': '13.6.1', 'device': '<<HKDevice: 0xab1021770>, name:EarPods, manufacturer:Apple Inc., localIdentifier:Wired Headphones, creation date:2020-08-30 20:08:43 +0000>', 'unit': 'dBASPL', 'creationDate': '2020-08-30 22:08:43 +0200', 'startDate': '2020-08-30 22:08:37 +0200', 'endDate': '2020-08-30 22:08:40 +0200', 'value': '62.366'}

 TYP: HKQuantityTypeIdentifierWalkingDoubleSupportPercentage
   Atrybuty: {'type': 'HKQuantityTypeIdentifierWalkingDoubleSupportPercentage', 'sourceName': 'iPhone', 'sourceVersion': '14.0', 'device': '<<HKDevice: 0xab1021310>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:14.0, creation date:2020-09-18 15:05:15 +0000>', 'unit': '%', 'creationDate': '2020-09-21 08:46:36 +0200', 'startDate': '2020-09-21 08:33:37 +0200', 'endDate': '2020-09-21 08:33:40 +0200', 'value': '0.329'}

 TYP: HKQuantityTypeIdentifierSixMinuteWalkTestDistance
   Atrybuty: {'type': 'HKQuantityTypeIdentifierSixMinuteWalkTestDistance', 'sourceName': 'iPhone', 'sourceVersion': '2890.12.17.0.3', 'unit': 'm', 'creationDate': '2024-03-14 17:50:03 +0200', 'startDate': '2024-03-14 17:50:03 +0200', 'endDate': '2024-03-14 17:50:03 +0200', 'value': '500'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKDateOfEarliestDataUsedForEstimate', 'value': '2024-03-02 23:00:00 +0000'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyAppleDeviceCalibrated', 'value': '1'}

 TYP: HKQuantityTypeIdentifierAppleStandTime
   Atrybuty: {'type': 'HKQuantityTypeIdentifierAppleStandTime', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '2890.8.3', 'unit': 'min', 'creationDate': '2024-03-03 17:20:11 +0200', 'startDate': '2024-03-03 17:15:00 +0200', 'endDate': '2024-03-03 17:20:00 +0200', 'value': '1'}

 TYP: HKQuantityTypeIdentifierWalkingSpeed
   Atrybuty: {'type': 'HKQuantityTypeIdentifierWalkingSpeed', 'sourceName': 'iPhone', 'sourceVersion': '14.0', 'device': '<<HKDevice: 0xab1021590>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:14.0, creation date:2020-09-18 15:05:15 +0000>', 'unit': 'km/hr', 'creationDate': '2020-09-21 08:46:36 +0200', 'startDate': '2020-09-21 08:33:37 +0200', 'endDate': '2020-09-21 08:33:40 +0200', 'value': '2.664'}

 TYP: HKQuantityTypeIdentifierWalkingStepLength
   Atrybuty: {'type': 'HKQuantityTypeIdentifierWalkingStepLength', 'sourceName': 'iPhone', 'sourceVersion': '14.0', 'device': '<<HKDevice: 0xab10227b0>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:14.0, creation date:2020-09-18 15:05:15 +0000>', 'unit': 'cm', 'creationDate': '2020-09-21 08:46:36 +0200', 'startDate': '2020-09-21 08:33:37 +0200', 'endDate': '2020-09-21 08:33:40 +0200', 'value': '47'}

 TYP: HKQuantityTypeIdentifierWalkingAsymmetryPercentage
   Atrybuty: {'type': 'HKQuantityTypeIdentifierWalkingAsymmetryPercentage', 'sourceName': 'iPhone', 'sourceVersion': '14.0', 'device': '<<HKDevice: 0xab1075b80>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:14.0, creation date:2020-09-18 15:05:15 +0000>', 'unit': '%', 'creationDate': '2020-09-21 09:39:37 +0200', 'startDate': '2020-09-21 08:35:02 +0200', 'endDate': '2020-09-21 08:35:19 +0200', 'value': '0'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyDevicePlacementSide', 'value': '2'}

 TYP: HKQuantityTypeIdentifierStairAscentSpeed
   Atrybuty: {'type': 'HKQuantityTypeIdentifierStairAscentSpeed', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '2890.8.3', 'unit': 'm/s', 'creationDate': '2024-03-04 09:04:47 +0200', 'startDate': '2024-03-04 09:03:56 +0200', 'endDate': '2024-03-04 09:04:05 +0200', 'value': '0.204918'}

 TYP: HKQuantityTypeIdentifierStairDescentSpeed
   Atrybuty: {'type': 'HKQuantityTypeIdentifierStairDescentSpeed', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '2890.8.3', 'unit': 'm/s', 'creationDate': '2024-03-04 10:43:24 +0200', 'startDate': '2024-03-04 10:42:44 +0200', 'endDate': '2024-03-04 10:42:48 +0200', 'value': '0.325972'}

 TYP: HKDataTypeSleepDurationGoal
   Atrybuty: {'type': 'HKDataTypeSleepDurationGoal', 'sourceName': 'Zdrowie', 'sourceVersion': '15.0', 'unit': 'hr', 'creationDate': '2021-10-04 13:32:04 +0200', 'startDate': '2021-10-04 13:32:04 +0200', 'endDate': '2021-10-04 13:32:04 +0200', 'value': '8'}

 TYP: HKQuantityTypeIdentifierAppleWalkingSteadiness
   Atrybuty: {'type': 'HKQuantityTypeIdentifierAppleWalkingSteadiness', 'sourceName': 'iPhone', 'sourceVersion': '2663.0.3', 'device': '<<HKDevice: 0xab1022b20>, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,1, software:15.0, creation date:2021-09-22 17:10:11 +0000>', 'unit': '%', 'creationDate': '2021-10-01 11:43:39 +0200', 'startDate': '2021-09-23 02:00:00 +0200', 'endDate': '2021-09-30 02:00:00 +0200', 'value': '0.980428'}

 TYP: HKQuantityTypeIdentifierAppleSleepingWristTemperature
   Atrybuty: {'type': 'HKQuantityTypeIdentifierAppleSleepingWristTemperature', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0xab1023e30>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': 'degC', 'creationDate': '2024-03-04 08:00:17 +0200', 'startDate': '2024-03-04 00:00:00 +0200', 'endDate': '2024-03-04 08:00:16 +0200', 'value': '36.5868'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKAlgorithmVersion', 'value': '1'}

 TYP: HKQuantityTypeIdentifierHeartRateRecoveryOneMinute
   Atrybuty: {'type': 'HKQuantityTypeIdentifierHeartRateRecoveryOneMinute', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '2890.12.17.1.1', 'unit': 'count/min', 'creationDate': '2024-03-26 19:21:24 +0200', 'startDate': '2024-03-26 19:21:12 +0200', 'endDate': '2024-03-26 19:21:12 +0200', 'value': '34.9111'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyUserMotionContext', 'value': '1'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeySessionEstimate', 'value': '24.2808 count/min'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyHeartRateRecoveryActivityDuration', 'value': '1587.05 s'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyHeartRateRecoveryTestType', 'value': '2'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate', 'value': '150 count/min'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKAlgorithmVersion', 'value': '1'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyHeartRateRecoveryActivityType', 'value': '52'}

 TYP: HKQuantityTypeIdentifierEnvironmentalSoundReduction
   Atrybuty: {'type': 'HKQuantityTypeIdentifierEnvironmentalSoundReduction', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0xab1021b30>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': 'dBASPL', 'creationDate': '2024-03-04 10:51:53 +0200', 'startDate': '2024-03-04 10:45:54 +0200', 'endDate': '2024-03-04 11:14:15 +0200', 'value': '23.6616'}

 TYP: HKQuantityTypeIdentifierTimeInDaylight
   Atrybuty: {'type': 'HKQuantityTypeIdentifierTimeInDaylight', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0xab1021ae0>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'unit': 'min', 'creationDate': '2024-03-04 13:39:30 +0200', 'startDate': '2024-03-04 13:26:41 +0200', 'endDate': '2024-03-04 13:31:41 +0200', 'value': '5'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyMaximumLightIntensity', 'value': '7385 lx'}

 TYP: HKQuantityTypeIdentifierPhysicalEffort
   Atrybuty: {'type': 'HKQuantityTypeIdentifierPhysicalEffort', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '2890.8.3', 'unit': 'kcal/hr·kg', 'creationDate': '2024-03-03 17:32:44 +0200', 'startDate': '2024-03-03 17:04:44 +0200', 'endDate': '2024-03-03 17:31:53 +0200', 'value': '1.6'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKActivityType', 'value': '3000'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKAlgorithmVersion', 'value': '1'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKPhysicalEffortEstimationType', 'value': '2'}

 TYP: HKCategoryTypeIdentifierSleepAnalysis
   Atrybuty: {'type': 'HKCategoryTypeIdentifierSleepAnalysis', 'sourceName': 'iPhone', 'sourceVersion': '15.0', 'creationDate': '2021-10-05 07:00:00 +0200', 'startDate': '2021-10-04 23:11:07 +0200', 'endDate': '2021-10-05 06:41:01 +0200', 'value': 'HKCategoryValueSleepAnalysisInBed'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKTimeZone', 'value': 'Europe/Warsaw'}

 TYP: HKCategoryTypeIdentifierAppleStandHour
   Atrybuty: {'type': 'HKCategoryTypeIdentifierAppleStandHour', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '10.3', 'device': '<<HKDevice: 0xab1023e30>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.3, creation date:2024-01-29 12:23:53 +0000>', 'creationDate': '2024-03-03 17:19:59 +0200', 'startDate': '2024-03-03 17:00:00 +0200', 'endDate': '2024-03-03 18:00:00 +0200', 'value': 'HKCategoryValueAppleStandHourStood'}

 TYP: HKCategoryTypeIdentifierMenstrualFlow
   Atrybuty: {'type': 'HKCategoryTypeIdentifierMenstrualFlow', 'sourceName': 'Zdrowie', 'sourceVersion': '15.0', 'creationDate': '2021-10-04 13:32:53 +0200', 'startDate': '2021-10-03 12:00:00 +0200', 'endDate': '2021-10-03 12:00:00 +0200', 'value': 'HKCategoryValueVaginalBleedingUnspecified'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMenstrualCycleStart', 'value': '1'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKWasUserEntered', 'value': '1'}

 TYP: HKCategoryTypeIdentifierHighHeartRateEvent
   Atrybuty: {'type': 'HKCategoryTypeIdentifierHighHeartRateEvent', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '11.4', 'device': '<<HKDevice: 0xab0f55180>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:11.4, creation date:2025-04-03 15:32:57 +0000>', 'creationDate': '2025-07-21 13:53:35 +0200', 'startDate': '2025-07-21 13:42:33 +0200', 'endDate': '2025-07-21 13:52:33 +0200', 'value': 'HKCategoryValueNotApplicable'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKHeartRateEventThreshold', 'value': '120 count/min'}

 TYP: HKCategoryTypeIdentifierAudioExposureEvent
   Atrybuty: {'type': 'HKCategoryTypeIdentifierAudioExposureEvent', 'sourceName': 'Apple\xa0Watch (Lol)', 'sourceVersion': '1', 'device': '<<HKDevice: 0xab0f57e30>, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch7,3, software:10.4, creation date:2024-03-23 21:29:37 +0000>', 'creationDate': '2024-05-24 17:16:06 +0200', 'startDate': '2024-05-24 17:13:08 +0200', 'endDate': '2024-05-24 17:16:06 +0200', 'value': 'HKCategoryValueEnvironmentalAudioExposureEventMomentaryLimit'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyAudioExposureLevel', 'value': '91.8655 dBASPL'}

 TYP: HKCategoryTypeIdentifierHeadphoneAudioExposureEvent
   Atrybuty: {'type': 'HKCategoryTypeIdentifierHeadphoneAudioExposureEvent', 'sourceName': 'iPhone', 'sourceVersion': '16.0.2', 'creationDate': '2022-12-04 15:31:26 +0200', 'startDate': '2022-11-27 05:43:02 +0200', 'endDate': '2022-12-04 15:31:26 +0200', 'value': 'HKCategoryValueHeadphoneAudioExposureEventSevenDayLimit'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyAudioExposureLevel', 'value': '93.8454 dBASPL'}
   typ: <MetadataEntry> atrybuty: {'key': 'HKMetadataKeyAudioExposureDuration', 'value': '5941.93 s'}


In [15]:
print(diff_types)
print(len(diff_types))

{'HKQuantityTypeIdentifierRespiratoryRate', 'HKQuantityTypeIdentifierWalkingDoubleSupportPercentage', 'HKCategoryTypeIdentifierSleepAnalysis', 'HKQuantityTypeIdentifierHeadphoneAudioExposure', 'HKWorkoutActivityTypePilates', 'HKQuantityTypeIdentifierBodyFatPercentage', 'HKWorkoutActivityTypeCycling', 'HKQuantityTypeIdentifierEnvironmentalSoundReduction', 'HKQuantityTypeIdentifierStairDescentSpeed', 'HKQuantityTypeIdentifierOxygenSaturation', 'HKQuantityTypeIdentifierAppleExerciseTime', 'HKQuantityTypeIdentifierWalkingAsymmetryPercentage', 'HKDataTypeSleepDurationGoal', 'HKQuantityTypeIdentifierHeight', 'ActivitySummary', 'HKQuantityTypeIdentifierAppleWalkingSteadiness', 'HKQuantityTypeIdentifierAppleSleepingWristTemperature', 'HKQuantityTypeIdentifierHeartRateRecoveryOneMinute', 'HKCategoryTypeIdentifierAudioExposureEvent', 'HKQuantityTypeIdentifierWalkingHeartRateAverage', 'HKQuantityTypeIdentifierEnvironmentalAudioExposure', 'HKQuantityTypeIdentifierDistanceCycling', 'HKQuantityTypeIdentifierSixMinuteWalkTestDistance', 'HKWorkoutActivityTypeWalking', 'HKCategoryTypeIdentifierHighHeartRateEvent', 'HKQuantityTypeIdentifierHeartRate', 'HKQuantityTypeIdentifierStepCount', 'InstantaneousBeatsPerMinute', 'HKQuantityTypeIdentifierBodyMass', 'HKWorkoutActivityTypeTennis', 'HKQuantityTypeIdentifierVO2Max', 'HKQuantityTypeIdentifierTimeInDaylight', 'HKWorkoutActivityTypeFunctionalStrengthTraining', 'HKQuantityTypeIdentifierRestingHeartRate', 'HKQuantityTypeIdentifierFlightsClimbed', 'HKCategoryTypeIdentifierMenstrualFlow', 'HKWorkoutActivityTypeStairClimbing', 'HKQuantityTypeIdentifierHeartRateVariabilitySDNN', 'HKQuantityTypeIdentifierWaistCircumference', 'HKQuantityTypeIdentifierBasalEnergyBurned', 'HKQuantityTypeIdentifierDistanceWalkingRunning', 'HKWorkoutActivityTypeCardioDance', 'HKWorkoutActivityTypeElliptical', 'HKCategoryTypeIdentifierAppleStandHour', 'HKCategoryTypeIdentifierHeadphoneAudioExposureEvent', 'HKQuantityTypeIdentifierStairAscentSpeed', 'HKQuantityTypeIdentifierWalkingStepLength', 'HKQuantityTypeIdentifierActiveEnergyBurned', 'HKQuantityTypeIdentifierAppleStandTime', 'HKQuantityTypeIdentifierPhysicalEffort', 'Me', 'HKQuantityTypeIdentifierWalkingSpeed'}
52

In [16]:
#Stworzenie dataframe z wybranym typem danych

short_names = {
    # --- CIAŁO / PODSTAWOWE ---
    'HKQuantityTypeIdentifierHeight': 'height',
    'HKQuantityTypeIdentifierBodyMass': 'weight',
    'HKQuantityTypeIdentifierWaistCircumference': 'waist',
    'HKQuantityTypeIdentifierBodyFatPercentage': 'fat_pct',

    # --- SERCE (HEART) ---
    'HKQuantityTypeIdentifierHeartRate': 'hr',
    'HKQuantityTypeIdentifierRestingHeartRate': 'rhr',
    'HKQuantityTypeIdentifierWalkingHeartRateAverage': 'hr_walk_avg',
    'HKQuantityTypeIdentifierHeartRateVariabilitySDNN': 'hrv',
    'HKQuantityTypeIdentifierHeartRateRecoveryOneMinute': 'hrr_1min',
    'HKCategoryTypeIdentifierHighHeartRateEvent': 'hr_high_event',

    # --- AKTYWNOŚĆ / ENERGIA ---
    'HKQuantityTypeIdentifierStepCount': 'steps',
    'HKQuantityTypeIdentifierDistanceWalkingRunning': 'dist_walk',
    'HKQuantityTypeIdentifierDistanceCycling': 'dist_cycle',
    'HKQuantityTypeIdentifierBasalEnergyBurned': 'kcal_basal',
    'HKQuantityTypeIdentifierActiveEnergyBurned': 'kcal_active',
    'HKQuantityTypeIdentifierFlightsClimbed': 'flights',
    'HKQuantityTypeIdentifierAppleExerciseTime': 'exercise_min',
    'HKQuantityTypeIdentifierAppleStandTime': 'stand_min',
    'HKCategoryTypeIdentifierAppleStandHour': 'stand_hr',
    'HKQuantityTypeIdentifierPhysicalEffort': 'effort',
    'HKQuantityTypeIdentifierVO2Max': 'vo2max',

    # --- MOBILNOŚĆ / CHÓD ---
    'HKQuantityTypeIdentifierWalkingSpeed': 'walk_speed',
    'HKQuantityTypeIdentifierWalkingStepLength': 'walk_step_len',
    'HKQuantityTypeIdentifierWalkingAsymmetryPercentage': 'walk_asym',
    'HKQuantityTypeIdentifierWalkingDoubleSupportPercentage': 'walk_dbl_supp',
    'HKQuantityTypeIdentifierStairAscentSpeed': 'stair_up_speed',
    'HKQuantityTypeIdentifierStairDescentSpeed': 'stair_down_speed',
    'HKQuantityTypeIdentifierAppleWalkingSteadiness': 'walk_steadiness',
    'HKQuantityTypeIdentifierSixMinuteWalkTestDistance': 'walk_6min',

    # --- ODDECH / POZIOMY ---
    'HKQuantityTypeIdentifierOxygenSaturation': 'spo2',
    'HKQuantityTypeIdentifierRespiratoryRate': 'resp_rate',

    # --- SEN ---
    'HKCategoryTypeIdentifierSleepAnalysis': 'sleep',
    'HKDataTypeSleepDurationGoal': 'sleep_goal',
    'HKQuantityTypeIdentifierAppleSleepingWristTemperature': 'wrist_temp',

    # --- ŚRODOWISKO / DŹWIĘK ---
    'HKQuantityTypeIdentifierEnvironmentalAudioExposure': 'audio_env',
    'HKQuantityTypeIdentifierHeadphoneAudioExposure': 'audio_hp',
    'HKQuantityTypeIdentifierEnvironmentalSoundReduction': 'sound_red',
    'HKCategoryTypeIdentifierAudioExposureEvent': 'audio_event',
    'HKCategoryTypeIdentifierHeadphoneAudioExposureEvent': 'audio_hp_event',
    'HKQuantityTypeIdentifierTimeInDaylight': 'daylight',

    # --- INNE ---
    'HKCategoryTypeIdentifierMenstrualFlow': 'menstr'
}

In [17]:
def load_one_type(file_path, tag_name, type_name=None):
    """
    Pobiera dane na podstawie samego tagu (np. 'ActivitySummary') lub tagu i typu (np. 'Record' + 'hr').
    Chirurgiczna pęseta do eksploracji danych.
    """
    health_data = []

    if file_path is None:
        return "Zła ścieżka pliku"

    context = ET.iterparse(file_path, events=("end",))

    for event, elem in context:

        if elem.tag == tag_name:
            current_type = elem.get('type') or elem.get('workoutActivityType')
            if type_name is None or current_type == type_name:
                record = dict(elem.attrib)

                for child in elem:
                    if child.tag == "MetadataEntry":
                        key = child.get('key')
                        if key is not None:
                            record[key] = child.get('value')
                health_data.append(record)

            elem.clear()

    if health_data:
        df = pd.DataFrame(health_data)
        if 'value' in df.columns:
            df['value'] = pd.to_numeric(df['value'], errors='coerce')
        for date_col in ['startDate', 'endDate', 'creationDate']:
            if date_col in df.columns:
                df[date_col] = pd.to_datetime(df[date_col])
        return df
    return pd.DataFrame()


df_hr = load_one_type(path, 'Record', 'HKQuantityTypeIdentifierHeartRate')
display(df_hr.head())

,type,sourceName,sourceVersion,unit,creationDate,startDate,endDate,value,device,HKMetadataKeyHeartRateMotionContext,HKMetadataKeySyncVersion,HKMetadataKeySyncIdentifier
0,HKQuantityTypeIdentifierHeartRate,Zepp Life,202112101619,count/min,2021-12-24 17:29:14+02:00,2021-12-17 01:00:00+02:00,2021-12-17 01:00:59+02:00,72.0,NaN,NaN,NaN,NaN
1,HKQuantityTypeIdentifierHeartRate,Zepp Life,202112101619,count/min,2021-12-24 17:29:14+02:00,2021-12-17 01:01:00+02:00,2021-12-17 01:01:59+02:00,70.0,NaN,NaN,NaN,NaN
2,HKQuantityTypeIdentifierHeartRate,Zepp Life,202112101619,count/min,2021-12-24 17:29:14+02:00,2021-12-17 01:02:00+02:00,2021-12-17 01:02:59+02:00,70.0,NaN,NaN,NaN,NaN
3,HKQuantityTypeIdentifierHeartRate,Zepp Life,202112101619,count/min,2021-12-24 17:29:14+02:00,2021-12-17 01:03:00+02:00,2021-12-17 01:03:59+02:00,69.0,NaN,NaN,NaN,NaN
4,HKQuantityTypeIdentifierHeartRate,Zepp Life,202112101619,count/min,2021-12-24 17:29:14+02:00,2021-12-17 01:04:00+02:00,2021-12-17 01:04:59+02:00,70.0,NaN,NaN,NaN,NaN

Analiza samych danych tetna

In [18]:
print(df_hr.columns)
print(df_hr.head())
print(df_hr.describe())

Index(['type', 'sourceName', 'sourceVersion', 'unit', 'creationDate',
       'startDate', 'endDate', 'value', 'device',
       'HKMetadataKeyHeartRateMotionContext', 'HKMetadataKeySyncVersion',
       'HKMetadataKeySyncIdentifier'],
      dtype='object')
                                type sourceName sourceVersion       unit  \
0  HKQuantityTypeIdentifierHeartRate  Zepp Life  202112101619  count/min
1  HKQuantityTypeIdentifierHeartRate  Zepp Life  202112101619  count/min
2  HKQuantityTypeIdentifierHeartRate  Zepp Life  202112101619  count/min
3  HKQuantityTypeIdentifierHeartRate  Zepp Life  202112101619  count/min
4  HKQuantityTypeIdentifierHeartRate  Zepp Life  202112101619  count/min

               creationDate                 startDate  \
0 2021-12-24 17:29:14+02:00 2021-12-17 01:00:00+02:00
1 2021-12-24 17:29:14+02:00 2021-12-17 01:01:00+02:00
2 2021-12-24 17:29:14+02:00 2021-12-17 01:02:00+02:00
3 2021-12-24 17:29:14+02:00 2021-12-17 01:03:00+02:00
4 2021-12-24 17:29:14+02:00 2021-12-17 01:04:00+02:00

                    endDate  value device HKMetadataKeyHeartRateMotionContext  \
0 2021-12-17 01:00:59+02:00   72.0    NaN                                 NaN
1 2021-12-17 01:01:59+02:00   70.0    NaN                                 NaN
2 2021-12-17 01:02:59+02:00   70.0    NaN                                 NaN
3 2021-12-17 01:03:59+02:00   69.0    NaN                                 NaN
4 2021-12-17 01:04:59+02:00   70.0    NaN                                 NaN

  HKMetadataKeySyncVersion HKMetadataKeySyncIdentifier
0                      NaN                         NaN
1                      NaN                         NaN
2                      NaN                         NaN
3                      NaN                         NaN
4                      NaN                         NaN
               value
count  422072.000000
mean       94.626144
std        29.074695
min        40.000000
25%        72.000000
50%        85.000000
75%       113.000000
max       195.000000

Czyścimy  dane - usuwamy kolumny w których wszystkie wartości sa nan

In [19]:
df_hr = df_hr.dropna(axis=1, how='all')

In [20]:
# Usuwamy konkretne kolumny techniczne, których nie potrzebujemy do analizy tętna
df_hr = df_hr.drop(columns=['HKMetadataKeySyncVersion', 'HKMetadataKeySyncIdentifier'], errors='ignore')

In [21]:
print(df_hr.columns)

Index(['type', 'sourceName', 'sourceVersion', 'unit', 'creationDate',
       'startDate', 'endDate', 'value', 'device',
       'HKMetadataKeyHeartRateMotionContext'],
      dtype='object')

In [22]:
# Usuwamy rekordy, które mają IDENTYCZNY start, koniec I wartość
df_hr = df_hr.drop_duplicates(subset=['startDate', 'endDate', 'value'])

print(f"Usunięto {len(df_hr) - len(df_hr)} idealnych duplikatów.")

Usunięto 0 idealnych duplikatów.

In [23]:

# bierzemy dane pobierane tylko z zegarka
df = df_hr[df_hr['sourceName'].str.contains('Apple', na=False)]


# Wywalamy rekordy, gdzie koniec jest przed początkiem i jakieś błędne
df = df[df['endDate'] >= df['startDate']]

# indeksujemy po dacie poczatkowej
df = df.set_index('startDate')

In [24]:
display(df.tail(100))

,type,sourceName,sourceVersion,unit,creationDate,endDate,value,device,HKMetadataKeyHeartRateMotionContext
startDate,,,,,,,,,
2026-04-05 21:27:10+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 21:27:14+02:00,2026-04-05 21:27:10+02:00,143.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",2
2026-04-05 21:27:18+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 21:27:19+02:00,2026-04-05 21:27:18+02:00,147.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",2
2026-04-05 21:27:23+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 21:27:24+02:00,2026-04-05 21:27:23+02:00,146.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",2
2026-04-05 21:27:26+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 21:27:29+02:00,2026-04-05 21:27:26+02:00,146.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",2
2026-04-05 21:27:32+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 21:27:34+02:00,2026-04-05 21:27:32+02:00,144.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",2
...,...,...,...,...,...,...,...,...,...
2026-04-05 22:31:51+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:37:52+02:00,2026-04-05 22:31:51+02:00,76.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",1
2026-04-05 22:37:49+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:43:35+02:00,2026-04-05 22:37:49+02:00,74.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",1
2026-04-05 22:43:16+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:45:34+02:00,2026-04-05 22:43:16+02:00,72.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",0
2026-04-05 22:45:26+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:51:13+02:00,2026-04-05 22:45:26+02:00,76.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",1
2026-04-05 22:51:01+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:58:15+02:00,2026-04-05 22:51:01+02:00,74.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",1

In [25]:

# 2. Definiujemy reguły: dla 'value' średnia, dla reszty 'pierwszy element'
# Tworzymy słownik, który dla każdej kolumny przypisuje funkcję 'first'
agg_rules = {col: 'first' for col in df.columns}

# Nadpisujemy regułę dla kolumny 'value' na 'mean'
if 'value' in agg_rules:
    agg_rules['value'] = 'mean'

# 3. Magiczne resamplowanie z regułami
df_minutowe = df.resample('1min').agg(agg_rules)

# 4. Przywracamy indeks do kolumny
df_minutowe = df_minutowe.reset_index()

display(df_minutowe)

,startDate,type,sourceName,sourceVersion,unit,creationDate,endDate,value,device,HKMetadataKeyHeartRateMotionContext
0,2024-03-03 17:10:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 17:10:31+02:00,2024-03-03 17:10:22+02:00,93.0,"<<HKDevice: 0xab0f57e30>, name:Apple Watch, ma...",1
1,2024-03-03 17:11:00+02:00,None,None,None,None,NaT,NaT,NaN,None,None
2,2024-03-03 17:12:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 17:16:07+02:00,2024-03-03 17:12:16+02:00,84.0,"<<HKDevice: 0xab0f57e30>, name:Apple Watch, ma...",1
3,2024-03-03 17:13:00+02:00,None,None,None,None,NaT,NaT,NaN,None,None
4,2024-03-03 17:14:00+02:00,None,None,None,None,NaT,NaT,NaN,None,None
...,...,...,...,...,...,...,...,...,...,...
1099057,2026-04-05 22:47:00+02:00,None,None,None,None,NaT,NaT,NaN,None,None
1099058,2026-04-05 22:48:00+02:00,None,None,None,None,NaT,NaT,NaN,None,None
1099059,2026-04-05 22:49:00+02:00,None,None,None,None,NaT,NaT,NaN,None,None
1099060,2026-04-05 22:50:00+02:00,None,None,None,None,NaT,NaT,NaN,None,None
1099061,2026-04-05 22:51:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:58:15+02:00,2026-04-05 22:51:01+02:00,74.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",1

In [27]:
df = df_minutowe.dropna()
display(df)

,startDate,type,sourceName,sourceVersion,unit,creationDate,endDate,value,device,HKMetadataKeyHeartRateMotionContext
0,2024-03-03 17:10:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 17:10:31+02:00,2024-03-03 17:10:22+02:00,93.0,"<<HKDevice: 0xab0f57e30>, name:Apple Watch, ma...",1
2,2024-03-03 17:12:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 17:16:07+02:00,2024-03-03 17:12:16+02:00,84.0,"<<HKDevice: 0xab0f57e30>, name:Apple Watch, ma...",1
8,2024-03-03 17:18:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 17:21:08+02:00,2024-03-03 17:18:43+02:00,82.0,"<<HKDevice: 0xab0f57e30>, name:Apple Watch, ma...",1
14,2024-03-03 17:24:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 17:25:36+02:00,2024-03-03 17:24:23+02:00,80.0,"<<HKDevice: 0xab0f57e30>, name:Apple Watch, ma...",1
15,2024-03-03 17:25:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 17:30:49+02:00,2024-03-03 17:25:28+02:00,78.0,"<<HKDevice: 0xab0f57e30>, name:Apple Watch, ma...",1
...,...,...,...,...,...,...,...,...,...,...
1099041,2026-04-05 22:31:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:37:52+02:00,2026-04-05 22:31:51+02:00,76.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",1
1099047,2026-04-05 22:37:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:43:35+02:00,2026-04-05 22:37:49+02:00,74.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",1
1099053,2026-04-05 22:43:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:45:34+02:00,2026-04-05 22:43:16+02:00,72.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",0
1099055,2026-04-05 22:45:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:51:13+02:00,2026-04-05 22:45:26+02:00,76.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",1
1099061,2026-04-05 22:51:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:58:15+02:00,2026-04-05 22:51:01+02:00,74.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",1

In [28]:

df.set_index('startDate', inplace=True)
df.sort_index(inplace=True)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 177180 entries, 2024-03-03 17:10:00+02:00 to 2026-04-05 22:51:00+02:00
Data columns (total 9 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   type                                 177180 non-null  object
 1   sourceName                           177180 non-null  object
 2   sourceVersion                        177180 non-null  object
 3   unit                                 177180 non-null  object
 4   creationDate                         177180 non-null  datetime64[ns, UTC+02:00]
 5   endDate                              177180 non-null  datetime64[ns, UTC+02:00]
 6   value                                177180 non-null  float64
 7   device                               177180 non-null  object
 8   HKMetadataKeyHeartRateMotionContext  177180 non-null  object
dtypes: datetime64[ns, UTC+02:00](2), float64(1), object(6)
memory usage: 13.5+ MB

In [30]:
df = df.dropna(subset=['value'])
print(df.info())
df

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 177180 entries, 2024-03-03 17:10:00+02:00 to 2026-04-05 22:51:00+02:00
Data columns (total 9 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   type                                 177180 non-null  object
 1   sourceName                           177180 non-null  object
 2   sourceVersion                        177180 non-null  object
 3   unit                                 177180 non-null  object
 4   creationDate                         177180 non-null  datetime64[ns, UTC+02:00]
 5   endDate                              177180 non-null  datetime64[ns, UTC+02:00]
 6   value                                177180 non-null  float64
 7   device                               177180 non-null  object
 8   HKMetadataKeyHeartRateMotionContext  177180 non-null  object
dtypes: datetime64[ns, UTC+02:00](2), float64(1), object(6)
memory usage: 13.5+ MB
None

,type,sourceName,sourceVersion,unit,creationDate,endDate,value,device,HKMetadataKeyHeartRateMotionContext
startDate,,,,,,,,,
2024-03-03 17:10:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 17:10:31+02:00,2024-03-03 17:10:22+02:00,93.0,"<<HKDevice: 0xab0f57e30>, name:Apple Watch, ma...",1
2024-03-03 17:12:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 17:16:07+02:00,2024-03-03 17:12:16+02:00,84.0,"<<HKDevice: 0xab0f57e30>, name:Apple Watch, ma...",1
2024-03-03 17:18:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 17:21:08+02:00,2024-03-03 17:18:43+02:00,82.0,"<<HKDevice: 0xab0f57e30>, name:Apple Watch, ma...",1
2024-03-03 17:24:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 17:25:36+02:00,2024-03-03 17:24:23+02:00,80.0,"<<HKDevice: 0xab0f57e30>, name:Apple Watch, ma...",1
2024-03-03 17:25:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 17:30:49+02:00,2024-03-03 17:25:28+02:00,78.0,"<<HKDevice: 0xab0f57e30>, name:Apple Watch, ma...",1
...,...,...,...,...,...,...,...,...,...
2026-04-05 22:31:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:37:52+02:00,2026-04-05 22:31:51+02:00,76.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",1
2026-04-05 22:37:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:43:35+02:00,2026-04-05 22:37:49+02:00,74.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",1
2026-04-05 22:43:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:45:34+02:00,2026-04-05 22:43:16+02:00,72.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",0
2026-04-05 22:45:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:51:13+02:00,2026-04-05 22:45:26+02:00,76.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",1
2026-04-05 22:51:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:58:15+02:00,2026-04-05 22:51:01+02:00,74.0,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",1

In [31]:
df.loc['2026-3-3':]

,type,sourceName,sourceVersion,unit,creationDate,endDate,value,device,HKMetadataKeyHeartRateMotionContext
startDate,,,,,,,,,
2026-03-03 00:00:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-03 00:04:23+02:00,2026-03-03 00:00:38+02:00,67.0000,"<<HKDevice: 0xab1076c10>, name:Apple Watch, ma...",0
2026-03-03 00:01:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-03 00:02:14+02:00,2026-03-03 00:01:12+02:00,75.5206,"<<HKDevice: 0xab1076c10>, name:Apple Watch, ma...",0
2026-03-03 00:04:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-03 00:09:28+02:00,2026-03-03 00:04:00+02:00,68.0000,"<<HKDevice: 0xab1076c10>, name:Apple Watch, ma...",0
2026-03-03 00:09:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-03 00:15:14+02:00,2026-03-03 00:09:12+02:00,74.0000,"<<HKDevice: 0xab1076c10>, name:Apple Watch, ma...",0
2026-03-03 00:14:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-03-03 00:56:07+02:00,2026-03-03 00:14:32+02:00,90.0000,"<<HKDevice: 0xab1076c10>, name:Apple Watch, ma...",0
...,...,...,...,...,...,...,...,...,...
2026-04-05 22:31:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:37:52+02:00,2026-04-05 22:31:51+02:00,76.0000,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",1
2026-04-05 22:37:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:43:35+02:00,2026-04-05 22:37:49+02:00,74.0000,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",1
2026-04-05 22:43:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:45:34+02:00,2026-04-05 22:43:16+02:00,72.0000,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",0
2026-04-05 22:45:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:51:13+02:00,2026-04-05 22:45:26+02:00,76.0000,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",1
2026-04-05 22:51:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),11.6.2,count/min,2026-04-05 22:58:15+02:00,2026-04-05 22:51:01+02:00,74.0000,"<<HKDevice: 0xab1023a70>, name:Apple Watch, ma...",1

In [32]:
df.loc['2024-03-01':'2024-03-05']

,type,sourceName,sourceVersion,unit,creationDate,endDate,value,device,HKMetadataKeyHeartRateMotionContext
startDate,,,,,,,,,
2024-03-03 17:10:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 17:10:31+02:00,2024-03-03 17:10:22+02:00,93.000,"<<HKDevice: 0xab0f57e30>, name:Apple Watch, ma...",1
2024-03-03 17:12:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 17:16:07+02:00,2024-03-03 17:12:16+02:00,84.000,"<<HKDevice: 0xab0f57e30>, name:Apple Watch, ma...",1
2024-03-03 17:18:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 17:21:08+02:00,2024-03-03 17:18:43+02:00,82.000,"<<HKDevice: 0xab0f57e30>, name:Apple Watch, ma...",1
2024-03-03 17:24:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 17:25:36+02:00,2024-03-03 17:24:23+02:00,80.000,"<<HKDevice: 0xab0f57e30>, name:Apple Watch, ma...",1
2024-03-03 17:25:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3,count/min,2024-03-03 17:30:49+02:00,2024-03-03 17:25:28+02:00,78.000,"<<HKDevice: 0xab0f57e30>, name:Apple Watch, ma...",1
...,...,...,...,...,...,...,...,...,...
2024-03-05 23:41:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3.1,count/min,2024-03-05 23:45:52+02:00,2024-03-05 23:41:47+02:00,67.000,"<<HKDevice: 0xab1092e40>, name:Apple Watch, ma...",0
2024-03-05 23:47:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3.1,count/min,2024-03-05 23:48:27+02:00,2024-03-05 23:47:57+02:00,65.000,"<<HKDevice: 0xab1092e40>, name:Apple Watch, ma...",1
2024-03-05 23:50:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3.1,count/min,2024-03-05 23:55:34+02:00,2024-03-05 23:50:10+02:00,63.000,"<<HKDevice: 0xab1092e40>, name:Apple Watch, ma...",1
2024-03-05 23:55:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3.1,count/min,2024-03-05 23:59:59+02:00,2024-03-05 23:55:17+02:00,63.000,"<<HKDevice: 0xab1092e40>, name:Apple Watch, ma...",1
2024-03-05 23:59:00+02:00,HKQuantityTypeIdentifierHeartRate,Apple Watch (Lol),10.3.1,count/min,2024-03-06 00:00:52+02:00,2024-03-05 23:59:51+02:00,66.648,"<<HKDevice: 0xab1092e40>, name:Apple Watch, ma...",0

# Analiza danych EKG
niestety nie ma ich w pliku XML, ale są w oddzielnym pliku CSV, który można pobrać z aplikacji Zdrowie. Zawiera próbki napięcia zarejestrowane podczas pomiaru EKG. Każdy wiersz reprezentuje jedną próbkę, z kolumnami 'sample' (numer próbki) i 'voltage' (napięcie w mV). Dane te są przydatne do analizy rytmu serca i wykrywania ewentualnych arytmii.

In [33]:
ekg_data = pd.read_csv("ekg.csv", skiprows=12, names=['sample', 'voltage'])